#include "stdafx.h"
#pragma warning(disable:4786)
#include "editor.h"
#include "editor_def.h"

#ifdef AFX_TARG_JPN

//グローバル変数
KEY_FUNC g_stKeyFunc[] =
{
	//ファイル系
	{"ファイル系",ID_FILE_NEW,"新規作成","新規にファイルを作成" },
	{"ファイル系",ID_FILE_OPEN,"開く","既存のファイルを開く" },
	{"ファイル系",ID_FILE_CLOSE,"閉じる","作業中のファイルを閉じる" },
	{"ファイル系",ID_FILE_SAVECLOSE,"上書き保存して閉じる","作業中のファイルを上書き保存して閉じる" },
	{"ファイル系",ID_FILE_SAVE,"上書き保存","作業中のファイルを上書き保存"},
	{"ファイル系",ID_FILE_SAVE_AS,"名前を付けて保存","作業中のファイルに名前を付けて保存"},
	{"ファイル系",ID_FILE_ALLSAVE,"すべて保存","すべてのファイルを保存"},
	{"ファイル系",ID_FILE_OPENONEXIT,"前回終了時のファイルを開く","前回終了時のファイルを開く"},
	{"ファイル系",ID_HTTP_FILE_OPEN,"WebサイトのHTMLファイルを開く","Webサイトから指定HTMLファイルをダウンロードしてソースを開く"},
	{"ファイル系",ID_FILE_REREAD,"再読み込み","現在アクティブなウインドウの内容をファイルから再び読み込みなおします"},
	{"ファイル系",ID_FILE_PROPERTY,"プロパティ","作業中の文書についての情報を表示します"},
	{"ファイル系",ID_FILE_OPENSAMENAME,"同じ名前のファイルを開く","カレントディレクトリにある、現在開いているファイルと（拡張子は違うが）同じ名前のファイルを開く"},
	{"ファイル系",ID_FILE_SHELLOPEN,"関連づけられたソフトで開く","現在開いているファイルを、関連づけられたソフトで開く"},
	{"ファイル系",ID_FILE_MOVE,"移動","現在開いているファイルを指定ディレクトリへ移動します"},
	{"ファイル系",ID_FILE_COPY,"コピー","現在開いているファイルを指定ディレクトリへコピーします"},
	{"ファイル系",ID_FILE_RENAME,"名前の変更","現在開いているファイルの名前を変更します"},
	{"ファイル系",ID_FILE_DELETE,"削除","現在開いているファイルを削除します"},
	{"ファイル系",ID_FILE_PRINT,"印刷","作業中のファイルを印刷"},
	{"ファイル系",ID_FILE_PRINT_PREVIEW,"印刷プレビュー","作業中ファイルの印刷イメージを表示"},
	{"ファイル系",ID_FILE_PRINT_SETUP,"プリンタの設定","プリンタ/印刷設定の変更"},
	{"ファイル系",ID_FILE_MRU_FILE1,"過去に開いたファイルＮｏ１を開く","MRU(Most Recently Used)ファイルの１番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE2,"過去に開いたファイルＮｏ２を開く","MRU(Most Recently Used)ファイルの２番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE3,"過去に開いたファイルＮｏ３を開く","MRU(Most Recently Used)ファイルの３番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE4,"過去に開いたファイルＮｏ４を開く","MRU(Most Recently Used)ファイルの４番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE5,"過去に開いたファイルＮｏ５を開く","MRU(Most Recently Used)ファイルの５番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE6,"過去に開いたファイルＮｏ６を開く","MRU(Most Recently Used)ファイルの６番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE7,"過去に開いたファイルＮｏ７を開く","MRU(Most Recently Used)ファイルの７番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE8,"過去に開いたファイルＮｏ８を開く","MRU(Most Recently Used)ファイルの８番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE9,"過去に開いたファイルＮｏ９を開く","MRU(Most Recently Used)ファイルの９番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE10,"過去に開いたファイルＮｏ１０を開く","MRU(Most Recently Used)ファイルの１０番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE11,"過去に開いたファイルＮｏ１１を開く","MRU(Most Recently Used)ファイルの１１番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE12,"過去に開いたファイルＮｏ１２を開く","MRU(Most Recently Used)ファイルの１２番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE13,"過去に開いたファイルＮｏ１３を開く","MRU(Most Recently Used)ファイルの１３番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE14,"過去に開いたファイルＮｏ１４を開く","MRU(Most Recently Used)ファイルの１４番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE15,"過去に開いたファイルＮｏ１５を開く","MRU(Most Recently Used)ファイルの１５番目を開く"},
	{"ファイル系",ID_FILE_MRU_FILE16,"過去に開いたファイルＮｏ１６を開く","MRU(Most Recently Used)ファイルの１６番目を開く"},
	{"ファイル系",ID_ALLSAVE_EXIT,"すべて保存し、終了","すべてのファイルを保存し、その後アプリケーションを終了"},
	{"ファイル系",ID_APP_EXIT,"アプリケーションの終了","アプリケーションを終了し、ファイルの保存を指示（キー割り当て変更不可）"},
	//編集系
	{"編集系",ID_EDIT_UNDO,"元に戻す","直前に行った動作を元に戻す"},
	{"編集系",ID_EDIT_REDO,"繰り返し","直前に行った動作を繰り返す"},
	{"編集系",ID_EDIT_CLEARUNDOBUF,"Undo/Redoバッファクリア","元に戻す、繰り返し用バッファをクリア"},
	{"編集系",ID_EDIT_ALLUNDO,"すべて元に戻す","今までに行った動作をすべて元に戻す"},
	{"編集系",ID_EDIT_ALLREDO,"すべて繰り返し","今までに行った動作をすべて繰り返し"},
	{"編集系",ID_EDIT_CUT,"切り取り","選択範囲を切り取ってクリップボードに保存"},
	{"編集系",ID_EDIT_COPY,"コピー","選択範囲をコピーしてクリップボードに保存"},
	{"編集系",ID_EDIT_PASTE,"貼り付け","クリップボードの内容を貼り付け"},
	{"編集系",ID_EDIT_DEL,"削除","選択範囲を削除します"},
	{"編集系",ID_EDIT_SELECTALL,"すべて選択","ドキュメント全体を選択"},
	{"編集系",ID_EDIT_CLIPVIEW,"クリップボードの中を見る","現在クリップボードの中にあるデータを見る"},
	{"編集系",ID_EDIT_BROWSEURL,"ＵＲＬをブラウズ","キャレット位置のＵＲＬをＷＥＢブラウザで表示します"},
	{"編集系",ID_EDIT_EXECMAILER,"メーラーを起動","キャレット位置のメールアドレスをもとにメーラーを起動します"},
	{"編集系",ID_EDIT_SETREADONLY,"書込み禁止にする","作業中の文書を書込み禁止に設定します"},
	{"編集系",ID_EDIT_UNSETREADONLY,"書込み禁止を解除する","作業中の文書の書込みを許可します"},
	{"編集系",ID_EDIT_INSDAY,"日付を挿入","キャレット位置に現在の日付文字列を挿入"},
	{"編集系",ID_EDIT_INSTIME,"時刻を挿入","キャレット位置に現在の時刻文字列を挿入"},
	{"編集系",ID_EDIT_CRLF,"DOS/Windows形式  CR+LF","ファイルの改行コードをＣＲ＋ＬＦにします。"},
	{"編集系",ID_EDIT_LF,"UNIX形式  LF","ファイルの改行コードをＬＦにします。"},
	{"編集系",ID_EDIT_CR,"Macintosh形式  CR","ファイルの改行コードをＣＲにします。"},
	{"編集系",ID_EDIT_CODE2EUC,"ＥＵＣコード","現在開いているファイルの全文をＥＵＣコードへ変換"},
	{"編集系",ID_EDIT_CODE2SJIS,"Ｓｈｉｆｔ－ＪＩＳコード","現在開いているファイルの全文をＳｈｉｆｔ－ＪＩＳコードへ変換"},
	{"編集系",ID_EDIT_CODE2JIS,"ＪＩＳコード","現在開いているファイルの全文をＪＩＳコードへ変換"},
	{"編集系",ID_EDIT_TAB2SPACE,"タブ－＞半角スペース","選択領域のタブを半角スペースに変換"},
	{"編集系",ID_EDIT_SPACE2TAB,"半角スペース－＞タブ","選択領域の半角スペースをタブに変換"},
	{"編集系",ID_EDIT_SPACE_ZEN2HAN,"全角スペース－＞半角スペース","選択領域の全角スペースを半角スペースに変換"},
	{"編集系",ID_EDIT_SPACE_HAN2ZEN,"半角スペース－＞全角スペース","選択領域の半角スペースを全角スペースに変換"},
	{"編集系",ID_EDIT_KATAKANA_HAN2ZEN,"半角ｶﾀｶﾅ－＞全角カタカナ","選択領域の半角ｶﾀｶﾅを全角カタカナに変換"},
	{"編集系",ID_EDIT_KATAKANA_ZEN2HAN,"全角カタカナ－＞半角ｶﾀｶﾅ","選択領域の全角カタカナを半角ｶﾀｶﾅに変換"},
	{"編集系",ID_EDIT_ALNUM_HAN2ZEN,"半角英数字－＞全角英数字","選択領域の半角英数字を全角英数字に変換"},
	{"編集系",ID_EDIT_ALNUM_ZEN2HAN,"全角英数字－＞半角英数字","選択領域の全角英数字を半角英数字に変換"},
	{"編集系",ID_EDIT_AL2UPPER,"英字－＞大文字","選択領域の半角英字を大文字に変換"},
	{"編集系",ID_EDIT_AL2LOWER,"英字－＞小文字","選択領域の半角英字を小文字に変換"},
	{"編集系",ID_EDIT_DELTOPSPACES,"先頭のスペース、タブを全て削除","選択領域内の先頭のスペース、タブを全て削除"},
	{"編集系",ID_EDIT_INSTAB,"タブをひとつ挿入","選択領域のインデントレベルを下げる"},
	{"編集系",ID_EDIT_DELTAB,"タブをひとつ削除","選択領域のインデントレベルを上げる"},
	{"編集系",ID_EDIT_INSCPPCOMMENT,"Ｃ／Ｃ＋＋行コメント( // )を挿入","選択領域の先頭にＣ／Ｃ＋＋の行コメント( // )を挿入"},
	{"編集系",ID_EDIT_DELCPPCOMMENT,"Ｃ／Ｃ＋＋行コメント( // )を削除","選択領域の先頭のＣ／Ｃ＋＋の行コメント( // )を削除"},
	{"編集系",ID_EDIT_INSVBCOMMENT,"ＶＢ行コメント( ' )を挿入","選択領域の先頭にＶＢの行コメント( ' )を挿入"},
	{"編集系",ID_EDIT_DELVBCOMMENT,"ＶＢ行コメント( ' )を削除","選択領域の先頭のＶＢの行コメント( ' )を削除"},
	{"編集系",ID_EDIT_INSASMCOMMENT,"アセンブラ行コメント( ; )を挿入","選択領域の先頭にアセンブラの行コメント( ; )を挿入"},
	{"編集系",ID_EDIT_DELASMCOMMENT,"アセンブラ行コメント( ; )を削除","選択領域の先頭のアセンブラの行コメント( ; )を削除"},
	{"編集系",ID_EDIT_INSQUOTE,"引用符号( > )を挿入","選択領域の先頭に引用符号( > )を挿入"},
	{"編集系",ID_EDIT_DELQUOTE,"引用符号( > )を削除","選択領域の先頭の引用符号( > )を削除"},
	//検索系
	{"検索系",ID_EDIT_FIND,"文字列の検索","指定した文字列の検索"},
	{"検索系",ID_EDIT_FINDCONTINUE,"文末方向へ検索続行","前回検索時と同一条件で文末方向へ検索を続行"},
	{"検索系",ID_EDIT_FINDREVCONTINUE,"文頭方向へ検索続行","前回検索時と同一条件で文頭方向へ検索を続行"},
	{"検索系",ID_EDIT_INCRIMENTALSEARCH,"インクリメンタルサーチ開始","インクリメンタルサーチの開始/終了"},
	{"検索系",ID_EDIT_REPLACE,"文字列の置換","指定した文字列を他の文字列で置換"},
	{"検索系",ID_EDIT_GREP,"ＧＲＥＰ","複数のファイルから文字列を検索"},
	{"検索系",ID_EDIT_FILECOMPARE,"ファイル比較","２つのテキストファイルを比較して相違個所の行を探します"},
	{"検索系",ID_EDIT_FCOMP_TABEQUAL2SPACE,"空白文字を区別しない","ファイル比較時に、空白文字を区別しない"},
	{"検索系",ID_EDIT_FCOMP_ZENEQUAL2HAN,"全角と半角を区別しない","ファイル比較時に、全角と半角を区別しない"},
	{"検索系",ID_EDIT_FCOMP_ALPHABETBIGANDSMALL,"英字の大文字小文字を区別しない","ファイル比較時に、英字の大文字小文字を区別しない"},
	{"検索系",ID_EDIT_NEXTDIFF,"次の相違個所へジャンプ","ファイル比較結果で判明した次の相違個所へジャンプ"},
	{"検索系",ID_EDIT_PREVDIFF,"前の相違個所へジャンプ","ファイル比較結果で判明した前の相違個所へジャンプ"},
	{"検索系",ID_EDIT_FILERECOMPARE,"ファイル再比較","現在の２つのテキストファイルを再度比較して相違個所の行を探します"},
	{"検索系",ID_EDIT_DIRCOMPARE,"ディレクトリ比較","２つのディレクトリを比較して個々のファイルの相違を探します"},
	{"検索系",ID_EDIT_DIRCMP_SYOSAI,"相違ファイルをさらに詳細に比較","ディレクトリ比較で相違ありと判定されたファイルを詳細比較"},
	//ジャンプ系
	{"ジャンプ系",ID_EDIT_JUMP2TOP,"先頭行へジャンプ","先頭行へジャンプ"},
	{"ジャンプ系",ID_EDIT_JUMP2BOTTOM,"最終行へジャンプ","最終行へジャンプ"},
	{"ジャンプ系",ID_EDIT_JUMP2LINE,"指定行へジャンプ","指定行へジャンプ"},
	{"ジャンプ系",ID_EDIT_JUMP2TOPSELECT,"先頭行へ選択ジャンプ","先頭行へ選択ジャンプ"},
	{"ジャンプ系",ID_EDIT_JUMP2BOTTOMSELECT,"最終行へ選択ジャンプ","最終行へ選択ジャンプ"},
	{"ジャンプ系",ID_PARENTHESIS,"対応する括弧へジャンプ","現在のキャレット位置の括弧と対応する括弧へジャンプ"},
	{"ジャンプ系",ID_PARENTHESIS_SELECT,"対応する括弧へ選択ジャンプ","現在のキャレット位置の括弧と対応する括弧へ選択ジャンプ"},
	{"ジャンプ系",ID_EDIT_TAGJUMP,"タグジャンプ","キャレット位置からタグ情報を取得してファイルを開く"},
	{"ジャンプ系",ID_JUMP_SETMARK,"現在行をマーク","キャレット位置の行をマークします"},
	{"ジャンプ系",ID_JUMP_DELMARK,"現在行のマーク解除","キャレット位置の行マークを解除します"},
	{"ジャンプ系",ID_JUMP_ALLDELMARK,"すべてのマーク解除","すべての行マークを解除します"},
	{"ジャンプ系",ID_JUMP_NEXTMARK,"次のマーク位置へジャンプ","キャレット位置よりも下にある次のマーク行へジャンプします"},
	{"ジャンプ系",ID_JUMP_PREVMARK,"前のマーク位置へジャンプ","キャレット位置よりも上にある前のマーク行へジャンプします"},
	{"ジャンプ系",ID_JUMP_MARKLIST,"マーク位置一覧表示","現在マークされている行を一覧表示します"},
	//表示系
	{"表示系",ID_VIEW_TOOLBAR,"標準ツールバー","標準ツールバーの表示/非表示"},
	{"表示系",ID_VIEW_TOOLBAR_EDIT,"編集関連ツールバー","編集関連ツールバーの表示/非表示"},
	{"表示系",ID_VIEW_TOOLBAR_FIND,"検索関連ツールバー","検索関連ツールバーの表示/非表示"},
	{"表示系",ID_VIEW_TOOLBAR_JMP,"ジャンプ関連ツールバー","ジャンプ関連ツールバーの表示/非表示"},
	{"表示系",ID_VIEW_TOOLBAR_TOOLS,"ツール関連ツールバー","ツール関連ツールバーの表示/非表示"},
	{"表示系",ID_VIEW_TOOLBAR_WND,"ウインドウ関連ツールバー","ウインドウ関連ツールバーの表示/非表示"},
	{"表示系",ID_VIEW_STATUS_BAR,"ステータスバー","ステータスバーの表示/非表示"},
	{"表示系",ID_VIEW_REDRAW,"リフレッシュ","現在のウインドウの内容表示をリフレッシュします"},
	{"表示系",ID_VIEW_LINENO,"行番号を表示","行番号を表示"},
	{"表示系",ID_VIEW_RULER,"ルーラを表示","ルーラを表示"},
	{"表示系",ID_VIEW_CRLF,"改行マークを表示","改行マークを表示"},
	{"表示系",ID_VIEW_TAB,"タブマークを表示","タブマークを表示"},
	{"表示系",ID_VIEW_ZENKAKUSPACE,"全角スペースを表示","全角スペースを表示"},
	{"表示系",ID_VIEW_UNDERLINE,"アンダーラインを表示","キャレット行にアンダーラインを表示"},
	{"表示系",ID_VIEW_EOF,"ＥＯＦマークを表示","ＥＯＦマークを表示"},
	{"表示系",ID_VIEW_CARET_IBEAM,"キャレット形状：縦棒","キャレット形状を縦棒にする"},
	{"表示系",ID_VIEW_CARET_SQUARE,"キャレット形状：箱型","キャレット形状を箱型にする"},
	{"表示系",ID_VIEW_TAB_2,"２タブ","タブサイズ：２タブ"},
	{"表示系",ID_VIEW_TAB_4,"４タブ","タブサイズ：４タブ"},
	{"表示系",ID_VIEW_TAB_8,"８タブ","タブサイズ：８タブ"},
	//ツール系
	{"ツール系",ID_FILE_SENDMAIL,"メール送信","現在開いている文書をそのままメールメッセージにして送信"},
	{"ツール系",ID_FILE_MAILLIST,"ＰＯＰ３サーバメール一覧","ＰＯＰ３サーバに受信済みのメール一覧を表示"},
	{"ツール系",ID_EDIT_ASCIIDUMP,"ＡＳＣＩＩコード表示ダンプ","現在アクティブなウインドウのファイルをＡＳＣＩＩコード表示でダンプします"},
	{"ツール系",ID_EDIT_SJISDUMP,"Ｓｈｉｆｔ-ＪＩＳコード表示ダンプ","現在アクティブなウインドウのファイルをＳｈｉｆｔ-ＪＩＳコード表示でダンプします"},
	{"ツール系",ID_EDIT_CODECONV,"文字コード変換","複数ファイルの文字コードを一括してＳＪＩＳ、ＥＵＣ、ＪＩＳコードへ変換します"},
	{"ツール系",ID_EDIT_KAIGYOCONV,"改行コード変換","複数ファイルの改行コードを一括してCR+LF、LF、CRへ変換します"},
	{"ツール系",ID_EDIT_WORDCOUNT,"ワードカウント","複数ファイルのバイト数、ワード数、行数を数えます"},
	{"ツール系",ID_EDIT_FILESEARCH,"ファイル検索","指定条件に一致するファイルを検索します"},
	{"ツール系",ID_EDIT_FILETOUCH,"ファイルへのタッチ","複数ファイルの最終更新日時を指定日時へ一括変更します"},
	{"ツール系",ID_EDIT_SOURCEARRANGE,"Ｃ／Ｃ＋＋言語ソース整形","Ｃ／Ｃ＋＋言語ソースのカッコやインデントを整形します"},
	{"ツール系",ID_SECURITY_ENCRIPT,"ファイル暗号化","ファイルを暗号化し、内容がわからないようにします"},
	{"ツール系",ID_SECURITY_DECRIPT,"ファイル復号化","ファイルを復号化し、内容がわかるようにします"},
	{"ツール系",ID_EDIT_UUENCODE,"ＵＵＥｎｃｏｄｅエンコード","指定ファイルをＵＵＥＮＣＯＤＥエンコードしてウインドウに表示"},
	{"ツール系",ID_EDIT_BASE64ENCODE,"Ｂａｓｅ６４エンコード","指定ファイルをＢａｓｅ６４エンコードしてウインドウに表示"},
	{"ツール系",ID_EDIT_QUOTEDENCODE,"Ｑｕｏｔｅｄ－Ｐｒｉｎｔａｂｌｅエンコード","指定ファイルをＱｕｏｔｅｄ－Ｐｒｉｎｔａｂｌｅエンコードしてウインドウに表示"},
	{"ツール系",ID_EDIT_UUDECODE,"ＵＵＤｅｃｏｄｅデコード","選択領域をＵＵＤＥＣＯＤＥデコードしてファイルへ保存"},
	{"ツール系",ID_EDIT_BASE64DECODE,"Ｂａｓｅ６４デコード","選択領域をＢａｓｅ６４デコードしてファイルへ保存"},
	{"ツール系",ID_EDIT_QUOTEDDECODE,"Ｑｕｏｔｅｄ－Ｐｒｉｎｔａｂｌｅデコード","選択領域をＱｕｏｔｅｄ－Ｐｒｉｎｔａｂｌｅデコードしてファイルへ保存"},
	{"ツール系",ID_TOOL_OPE_STARTENDRECORD,"キー操作の記録開始/終了","キー操作の記録を開始/終了"},
	{"ツール系",ID_TOOL_OPE_DO,"キー操作の実行","記録されているキー操作を実行"},
	{"ツール系",ID_TOOL_OPE_STEPDO_NEXT,"次のキー操作","記録されている次のキー操作をステップ実行"},
	{"ツール系",ID_TOOL_OPE_STEPDO_END,"キー操作のステップ実行を終了","記録されているキー操作のステップ実行を終了"},
	{"ツール系",ID_TOOL_OPE_SAVE,"キー操作をファイルへ保存","記録されているキー操作をファイルへ保存"},
	{"ツール系",ID_TOOL_OPE_OPEN,"キー操作をファイルから読み込む","ファイル保存されているキー操作を読み込む"},
	{"ツール系",ID_TOOL_OPE_DISP,"キー操作の内容を表示","記録されているキー操作を一覧表示"},
	//設定系
	{"設定系",ID_SETTINGS,"設定","設定"},
	{"設定系",ID_CUSTOMIZE_TOOLBAR,"標準ツールバーのカスタマイズ","標準ツールバーのボタン並びをカスタマイズします"},
	{"設定系",ID_CUSTOMIZE_TOOLBAREDIT,"編集関連ツールバーのカスタマイズ","編集関連ツールバーのボタン並びをカスタマイズします"},
	{"設定系",ID_CUSTOMIZE_TOOLBARFIND,"検索関連ツールバーのカスタマイズ","検索関連ツールバーのボタン並びをカスタマイズします"},
	{"設定系",ID_CUSTOMIZE_TOOLBARJMP,"ジャンプ関連ツールバーのカスタマイズ","ジャンプ関連ツールバーのボタン並びをカスタマイズします"},
	{"設定系",ID_CUSTOMIZE_TOOLBARTOOLS,"ツール関連ツールバーのカスタマイズ","ツール関連ツールバーのボタン並びをカスタマイズします"},
	{"設定系",ID_CUSTOMIZE_TOOLBARWND,"ウインドウ関連ツールバーのカスタマイズ","ウインドウ関連ツールバーのボタン並びをカスタマイズします"},
	//ウインドウ系
	{"ウインドウ系",ID_WINDOW_NEW,"新しいウインドウを開く","作業中のウインドウを複写して表示"},
	{"ウインドウ系",ID_WINDOW_SPLIT,"分割","作業中のウインドウを分割"},
	{"ウインドウ系",ID_WINDOW_ARRANGE,"アイコンの整列","ウインドウの下部にアイコンを整列"},
	{"ウインドウ系",ID_WINDOW_MINIMIZE,"最小化","ウインドウのアイコン化"},
	{"ウインドウ系",ID_WINDOW_MAXIMIZE,"最大化","ウインドウを最大表示にする"},
	{"ウインドウ系",ID_WINDOW_RESTORE,"もとのサイズに戻す","アイコン化または最大表示されているウインドウを元のサイズと位置に戻す"},
	{"ウインドウ系",ID_WND_NEXT,"次のウインドウ","ＭＤＩの次のウインドウに移動（キー割り当て変更不可）"},
	{"ウインドウ系",ID_WND_PREV,"前のウインドウ","ＭＤＩの前のウインドウに移動"},
	{"ウインドウ系",ID_NEXT_PANE,"次のペイン","スプリッタウインドウの次のペインに切り替える"},
	{"ウインドウ系",ID_PREV_PANE,"前のペイン","スプリッタウインドウの前のペインに切り替える"},
	{"ウインドウ系",ID_WINDOW_CASCADE,"重ねて表示","ウインドウを重ねて表示"},
	{"ウインドウ系",ID_WINDOW_TILE_HORZ,"上下に並べて表示","ウインドウを上下に並べて表示"},
	{"ウインドウ系",ID_WINDOW_TILE_VERT,"左右に並べて表示","ウインドウを左右に並べて表示"},
	{"ウインドウ系",ID_WINDOW_CLOSE,"閉じる","ウインドウを閉じる（キー割り当て変更不可）"},
	{"ウインドウ系",ID_WINDOW_ALLCLOSE,"すべて閉じる","すべてのウインドウを閉じる"},
	//ヘルプ系
	{"ヘルプ系",ID_HELP_CONTENT,"目次","ヘルプの目次を表示"},
	{"ヘルプ系",ID_HELP_CONTENT2,"ＨＴＭＬヘルプ目次","ＨＴＭＬヘルプの目次を表示"},
	{"ヘルプ系",ID_APP_ABOUT,"バージョン情報","プログラムの情報、バージョンそして著作権を表示"},
	{"ヘルプ系",ID_HELP_LICENSE,"ライセンス登録","ユーザ情報入力、ライセンスＩＤの登録"},
	//その他系
	{"その他系",ID_WORDSKIP2LEFT,"左方向ワードスキップ","キャレットを左方向へワードスキップ"},
	{"その他系",ID_WORDSKIP2RIGHT,"右方向ワードスキップ","キャレットを右方向へワードスキップ"},
	{"その他系",ID_WORDSELECT2LEFT,"左方向ワードセレクト","キャレットを左方向へワードセレクト"},
	{"その他系",ID_WORDSELECT2RIGHT,"右方向ワードセレクト","キャレットを右方向へワードセレクト"},
	{"",0,"",""}
};
		
KEY g_stKeys[] = 
{
	//キー修飾なし
	{VK_F1,"F1",FALSE,FALSE,FALSE},
	{VK_F2,"F2",FALSE,FALSE,FALSE},
	{VK_F3,"F3",FALSE,FALSE,FALSE},
	{VK_F4,"F4",FALSE,FALSE,FALSE},
	{VK_F5,"F5",FALSE,FALSE,FALSE},
	{VK_F6,"F6",FALSE,FALSE,FALSE},
	{VK_F7,"F7",FALSE,FALSE,FALSE},
	{VK_F8,"F8",FALSE,FALSE,FALSE},
	{VK_F9,"F9",FALSE,FALSE,FALSE},
	{VK_F10,"F10",FALSE,FALSE,FALSE},
	{VK_F11,"F11",FALSE,FALSE,FALSE},
	{VK_F12,"F12",FALSE,FALSE,FALSE},
	//Ａｌｔキー修飾あり
	{VK_F1,"Alt+F1",FALSE,FALSE,TRUE},
	{VK_F2,"Alt+F2",FALSE,FALSE,TRUE},
	{VK_F3,"Alt+F3",FALSE,FALSE,TRUE},
	{VK_F4,"Alt+F4",FALSE,FALSE,TRUE},
	{VK_F5,"Alt+F5",FALSE,FALSE,TRUE},
	{VK_F6,"Alt+F6",FALSE,FALSE,TRUE},
	{VK_F7,"Alt+F7",FALSE,FALSE,TRUE},
	{VK_F8,"Alt+F8",FALSE,FALSE,TRUE},
	{VK_F9,"Alt+F9",FALSE,FALSE,TRUE},
	{VK_F10,"Alt+F10",FALSE,FALSE,TRUE},
	{VK_F11,"Alt+F11",FALSE,FALSE,TRUE},
	{VK_F12,"Alt+F12",FALSE,FALSE,TRUE},
	{'0',"Alt+0",FALSE,FALSE,TRUE},
	{'1',"Alt+1",FALSE,FALSE,TRUE},
	{'2',"Alt+2",FALSE,FALSE,TRUE},
	{'3',"Alt+3",FALSE,FALSE,TRUE},
	{'4',"Alt+4",FALSE,FALSE,TRUE},
	{'5',"Alt+5",FALSE,FALSE,TRUE},
	{'6',"Alt+6",FALSE,FALSE,TRUE},
	{'7',"Alt+7",FALSE,FALSE,TRUE},
	{'8',"Alt+8",FALSE,FALSE,TRUE},
	{'9',"Alt+9",FALSE,FALSE,TRUE},
	{VK_END,"Alt+End",FALSE,FALSE,TRUE},
	{VK_HOME,"Alt+Home",FALSE,FALSE,TRUE},
	{VK_LEFT,"Alt+←",FALSE,FALSE,TRUE},
	{VK_RIGHT,"Alt+→",FALSE,FALSE,TRUE},
	{VK_UP,"Alt+↑",FALSE,FALSE,TRUE},
	{VK_DOWN,"Alt+↓",FALSE,FALSE,TRUE},
	{VK_PRIOR,"Alt+PgUp",FALSE,FALSE,TRUE},
	{VK_NEXT,"Alt+PgDn",FALSE,FALSE,TRUE},
	{VK_INSERT,"Alt+Ins",FALSE,FALSE,TRUE},
	{VK_DELETE,"Alt+Del",FALSE,FALSE,TRUE},
	{VK_BACK,"Alt+Back",FALSE,FALSE,TRUE},
	{VK_RETURN,"Alt+Ret",FALSE,FALSE,TRUE},
	//Ｓｈｉｆｔキー修飾あり
	{VK_F1,"Shft+F1",FALSE,TRUE,FALSE},
	{VK_F2,"Shft+F2",FALSE,TRUE,FALSE},
	{VK_F3,"Shft+F3",FALSE,TRUE,FALSE},
	{VK_F4,"Shft+F4",FALSE,TRUE,FALSE},
	{VK_F5,"Shft+F5",FALSE,TRUE,FALSE},
	{VK_F6,"Shft+F6",FALSE,TRUE,FALSE},
	{VK_F7,"Shft+F7",FALSE,TRUE,FALSE},
	{VK_F8,"Shft+F8",FALSE,TRUE,FALSE},
	{VK_F9,"Shft+F9",FALSE,TRUE,FALSE},
	{VK_F10,"Shft+F10",FALSE,TRUE,FALSE},
	{VK_F11,"Shft+F11",FALSE,TRUE,FALSE},
	{VK_F12,"Shft+F12",FALSE,TRUE,FALSE},
	{VK_INSERT,"Shft+Ins",FALSE,TRUE,FALSE},
	{VK_DELETE,"Shft+Del",FALSE,TRUE,FALSE},
	{VK_BACK,"Shft+Back",FALSE,TRUE,FALSE},
	{VK_RETURN,"Shft+Ret",FALSE,TRUE,FALSE},
	//Ｃｔｒｌキー修飾あり
	{VK_F1,"Ctl+F1",TRUE,FALSE,FALSE},
	{VK_F2,"Ctl+F2",TRUE,FALSE,FALSE},
	{VK_F3,"Ctl+F3",TRUE,FALSE,FALSE},
	{VK_F4,"Ctl+F4",TRUE,FALSE,FALSE},
	{VK_F5,"Ctl+F5",TRUE,FALSE,FALSE},
	{VK_F6,"Ctl+F6",TRUE,FALSE,FALSE},
	{VK_F7,"Ctl+F7",TRUE,FALSE,FALSE},
	{VK_F8,"Ctl+F8",TRUE,FALSE,FALSE},
	{VK_F9,"Ctl+F9",TRUE,FALSE,FALSE},
	{VK_F10,"Ctl+F10",TRUE,FALSE,FALSE},
	{VK_F11,"Ctl+F11",TRUE,FALSE,FALSE},
	{VK_F12,"Ctl+F12",TRUE,FALSE,FALSE},
	{'A',"Ctl+A",TRUE,FALSE,FALSE},
	{'B',"Ctl+B",TRUE,FALSE,FALSE},
	{'C',"Ctl+C",TRUE,FALSE,FALSE},
	{'D',"Ctl+D",TRUE,FALSE,FALSE},
	{'E',"Ctl+E",TRUE,FALSE,FALSE},
	{'F',"Ctl+F",TRUE,FALSE,FALSE},
	{'G',"Ctl+G",TRUE,FALSE,FALSE},
	{'H',"Ctl+H",TRUE,FALSE,FALSE},
	{'I',"Ctl+I",TRUE,FALSE,FALSE},
	{'J',"Ctl+J",TRUE,FALSE,FALSE},
	{'K',"Ctl+K",TRUE,FALSE,FALSE},
	{'L',"Ctl+L",TRUE,FALSE,FALSE},
	{'M',"Ctl+M",TRUE,FALSE,FALSE},
	{'N',"Ctl+N",TRUE,FALSE,FALSE},
	{'O',"Ctl+O",TRUE,FALSE,FALSE},
	{'P',"Ctl+P",TRUE,FALSE,FALSE},
	{'Q',"Ctl+Q",TRUE,FALSE,FALSE},
	{'R',"Ctl+R",TRUE,FALSE,FALSE},
	{'S',"Ctl+S",TRUE,FALSE,FALSE},
	{'T',"Ctl+T",TRUE,FALSE,FALSE},
	{'U',"Ctl+U",TRUE,FALSE,FALSE},
	{'V',"Ctl+V",TRUE,FALSE,FALSE},
	{'W',"Ctl+W",TRUE,FALSE,FALSE},
	{'X',"Ctl+X",TRUE,FALSE,FALSE},
	{'Y',"Ctl+Y",TRUE,FALSE,FALSE},
	{'Z',"Ctl+Z",TRUE,FALSE,FALSE},
	{'0',"Ctl+0",TRUE,FALSE,FALSE},
	{'1',"Ctl+1",TRUE,FALSE,FALSE},
	{'2',"Ctl+2",TRUE,FALSE,FALSE},
	{'3',"Ctl+3",TRUE,FALSE,FALSE},
	{'4',"Ctl+4",TRUE,FALSE,FALSE},
	{'5',"Ctl+5",TRUE,FALSE,FALSE},
	{'6',"Ctl+6",TRUE,FALSE,FALSE},
	{'7',"Ctl+7",TRUE,FALSE,FALSE},
	{'8',"Ctl+8",TRUE,FALSE,FALSE},
	{'9',"Ctl+9",TRUE,FALSE,FALSE},
	{VK_END,"Ctl+End",TRUE,FALSE,FALSE},
	{VK_HOME,"Ctl+Home",TRUE,FALSE,FALSE},
	{VK_LEFT,"Ctl+←",TRUE,FALSE,FALSE},
	{VK_RIGHT,"Ctl+→",TRUE,FALSE,FALSE},
	{VK_UP,"Ctl+↑",TRUE,FALSE,FALSE},
	{VK_DOWN,"Ctl+↓",TRUE,FALSE,FALSE},
	{VK_PRIOR,"Ctl+PgUp",TRUE,FALSE,FALSE},
	{VK_NEXT,"Ctl+PgDn",TRUE,FALSE,FALSE},
	{VK_INSERT,"Ctl+Ins",TRUE,FALSE,FALSE},
	{VK_DELETE,"Ctl+Del",TRUE,FALSE,FALSE},
	{VK_BACK,"Ctl+Back",TRUE,FALSE,FALSE},
	{VK_RETURN,"Ctl+Ret",TRUE,FALSE,FALSE},
	//ＳｈｉｆｔＣｔｒｌキー修飾あり
	{VK_F1,"Shft+Ctl+F1",TRUE,TRUE,FALSE},
	{VK_F2,"Shft+Ctl+F2",TRUE,TRUE,FALSE},
	{VK_F3,"Shft+Ctl+F3",TRUE,TRUE,FALSE},
	{VK_F4,"Shft+Ctl+F4",TRUE,TRUE,FALSE},
	{VK_F5,"Shft+Ctl+F5",TRUE,TRUE,FALSE},
	{VK_F6,"Shft+Ctl+F6",TRUE,TRUE,FALSE},
	{VK_F7,"Shft+Ctl+F7",TRUE,TRUE,FALSE},
	{VK_F8,"Shft+Ctl+F8",TRUE,TRUE,FALSE},
	{VK_F9,"Shft+Ctl+F9",TRUE,TRUE,FALSE},
	{VK_F10,"Shft+Ctl+F10",TRUE,TRUE,FALSE},
	{VK_F11,"Shft+Ctl+F11",TRUE,TRUE,FALSE},
	{VK_F12,"Shft+Ctl+F12",TRUE,TRUE,FALSE},
	{'A',"Shft+Ctl+A",TRUE,TRUE,FALSE},
	{'B',"Shft+Ctl+B",TRUE,TRUE,FALSE},
	{'C',"Shft+Ctl+C",TRUE,TRUE,FALSE},
	{'D',"Shft+Ctl+D",TRUE,TRUE,FALSE},
	{'E',"Shft+Ctl+E",TRUE,TRUE,FALSE},
	{'F',"Shft+Ctl+F",TRUE,TRUE,FALSE},
	{'G',"Shft+Ctl+G",TRUE,TRUE,FALSE},
	{'H',"Shft+Ctl+H",TRUE,TRUE,FALSE},
	{'I',"Shft+Ctl+I",TRUE,TRUE,FALSE},
	{'J',"Shft+Ctl+J",TRUE,TRUE,FALSE},
	{'K',"Shft+Ctl+K",TRUE,TRUE,FALSE},
	{'L',"Shft+Ctl+L",TRUE,TRUE,FALSE},
	{'M',"Shft+Ctl+M",TRUE,TRUE,FALSE},
	{'N',"Shft+Ctl+N",TRUE,TRUE,FALSE},
	{'O',"Shft+Ctl+O",TRUE,TRUE,FALSE},
	{'P',"Shft+Ctl+P",TRUE,TRUE,FALSE},
	{'Q',"Shft+Ctl+Q",TRUE,TRUE,FALSE},
	{'R',"Shft+Ctl+R",TRUE,TRUE,FALSE},
	{'S',"Shft+Ctl+S",TRUE,TRUE,FALSE},
	{'T',"Shft+Ctl+T",TRUE,TRUE,FALSE},
	{'U',"Shft+Ctl+U",TRUE,TRUE,FALSE},
	{'V',"Shft+Ctl+V",TRUE,TRUE,FALSE},
	{'W',"Shft+Ctl+W",TRUE,TRUE,FALSE},
	{'X',"Shft+Ctl+X",TRUE,TRUE,FALSE},
	{'Y',"Shft+Ctl+Y",TRUE,TRUE,FALSE},
	{'Z',"Shft+Ctl+Z",TRUE,TRUE,FALSE},
	{'0',"Shft+Ctl+0",TRUE,TRUE,FALSE},
	{'1',"Shft+Ctl+1",TRUE,TRUE,FALSE},
	{'2',"Shft+Ctl+2",TRUE,TRUE,FALSE},
	{'3',"Shft+Ctl+3",TRUE,TRUE,FALSE},
	{'4',"Shft+Ctl+4",TRUE,TRUE,FALSE},
	{'5',"Shft+Ctl+5",TRUE,TRUE,FALSE},
	{'6',"Shft+Ctl+6",TRUE,TRUE,FALSE},
	{'7',"Shft+Ctl+7",TRUE,TRUE,FALSE},
	{'8',"Shft+Ctl+8",TRUE,TRUE,FALSE},
	{'9',"Shft+Ctl+9",TRUE,TRUE,FALSE},
	{VK_END,"Shft+Ctl+End",TRUE,TRUE,FALSE},
	{VK_HOME,"Shft+Ctl+Home",TRUE,TRUE,FALSE},
	{VK_LEFT,"Shft+Ctl+←",TRUE,TRUE,FALSE},
	{VK_RIGHT,"Shft+Ctl+→",TRUE,TRUE,FALSE},
	{VK_UP,"Shft+Ctl+↑",TRUE,TRUE,FALSE},
	{VK_DOWN,"Shft+Ctl+↓",TRUE,TRUE,FALSE},
	{VK_PRIOR,"Shft+Ctl+PgUp",TRUE,TRUE,FALSE},
	{VK_NEXT,"Shft+Ctl+PgDn",TRUE,TRUE,FALSE},
	{VK_INSERT,"Shft+Ctl+Ins",TRUE,TRUE,FALSE},
	{VK_DELETE,"Shft+Ctl+Del",TRUE,TRUE,FALSE},
	{VK_BACK,"Shft+Ctl+Back",TRUE,TRUE,FALSE},
	{VK_RETURN,"Shft+Ctl+Ret",TRUE,TRUE,FALSE},
	//Ｃｔｒｌ＋Ａｌｔキー修飾あり
	{VK_F1,"Ctl+Alt+F1",TRUE,FALSE,TRUE},
	{VK_F2,"Ctl+Alt+F2",TRUE,FALSE,TRUE},
	{VK_F3,"Ctl+Alt+F3",TRUE,FALSE,TRUE},
	{VK_F4,"Ctl+Alt+F4",TRUE,FALSE,TRUE},
	{VK_F5,"Ctl+Alt+F5",TRUE,FALSE,TRUE},
	{VK_F6,"Ctl+Alt+F6",TRUE,FALSE,TRUE},
	{VK_F7,"Ctl+Alt+F7",TRUE,FALSE,TRUE},
	{VK_F8,"Ctl+Alt+F8",TRUE,FALSE,TRUE},
	{VK_F9,"Ctl+Alt+F9",TRUE,FALSE,TRUE},
	{VK_F10,"Ctl+Alt+F10",TRUE,FALSE,TRUE},
	{VK_F11,"Ctl+Alt+F11",TRUE,FALSE,TRUE},
	{VK_F12,"Ctl+Alt+F12",TRUE,FALSE,TRUE},
	{'0',"Ctl+Alt+0",TRUE,FALSE,TRUE},
	{'1',"Ctl+Alt+1",TRUE,FALSE,TRUE},
	{'2',"Ctl+Alt+2",TRUE,FALSE,TRUE},
	{'3',"Ctl+Alt+3",TRUE,FALSE,TRUE},
	{'4',"Ctl+Alt+4",TRUE,FALSE,TRUE},
	{'5',"Ctl+Alt+5",TRUE,FALSE,TRUE},
	{'6',"Ctl+Alt+6",TRUE,FALSE,TRUE},
	{'7',"Ctl+Alt+7",TRUE,FALSE,TRUE},
	{'8',"Ctl+Alt+8",TRUE,FALSE,TRUE},
	{'9',"Ctl+Alt+9",TRUE,FALSE,TRUE},
	{VK_END,"Ctl+Alt+End",TRUE,FALSE,TRUE},
	{VK_HOME,"Ctl+Alt+Home",TRUE,FALSE,TRUE},
	{VK_LEFT,"Ctl+Alt+←",TRUE,FALSE,TRUE},
	{VK_RIGHT,"Ctl+Alt+→",TRUE,FALSE,TRUE},
	{VK_UP,"Ctl+Alt+↑",TRUE,FALSE,TRUE},
	{VK_DOWN,"Ctl+Alt+↓",TRUE,FALSE,TRUE},
	{VK_PRIOR,"Ctl+Alt+PgUp",TRUE,FALSE,TRUE},
	{VK_NEXT,"Ctl+Alt+PgDn",TRUE,FALSE,TRUE},
	{VK_INSERT,"Ctl+Alt+Ins",TRUE,FALSE,TRUE},
	{VK_BACK,"Ctl+Alt+Back",TRUE,FALSE,TRUE},
	{VK_RETURN,"Ctl+Alt+Ret",TRUE,FALSE,TRUE},
	//Ｓｈｉｆｔ＋Ａｌｔキー修飾あり
	{VK_F1,"Shft+Alt+F1",FALSE,TRUE,TRUE},
	{VK_F2,"Shft+Alt+F2",FALSE,TRUE,TRUE},
	{VK_F3,"Shft+Alt+F3",FALSE,TRUE,TRUE},
	{VK_F4,"Shft+Alt+F4",FALSE,TRUE,TRUE},
	{VK_F5,"Shft+Alt+F5",FALSE,TRUE,TRUE},
	{VK_F6,"Shft+Alt+F6",FALSE,TRUE,TRUE},
	{VK_F7,"Shft+Alt+F7",FALSE,TRUE,TRUE},
	{VK_F8,"Shft+Alt+F8",FALSE,TRUE,TRUE},
	{VK_F9,"Shft+Alt+F9",FALSE,TRUE,TRUE},
	{VK_F10,"Shft+Alt+F10",FALSE,TRUE,TRUE},
	{VK_F11,"Shft+Alt+F11",FALSE,TRUE,TRUE},
	{VK_F12,"Shft+Alt+F12",FALSE,TRUE,TRUE},
	{'0',"Shft+Alt+0",FALSE,TRUE,TRUE},
	{'1',"Shft+Alt+1",FALSE,TRUE,TRUE},
	{'2',"Shft+Alt+2",FALSE,TRUE,TRUE},
	{'3',"Shft+Alt+3",FALSE,TRUE,TRUE},
	{'4',"Shft+Alt+4",FALSE,TRUE,TRUE},
	{'5',"Shft+Alt+5",FALSE,TRUE,TRUE},
	{'6',"Shft+Alt+6",FALSE,TRUE,TRUE},
	{'7',"Shft+Alt+7",FALSE,TRUE,TRUE},
	{'8',"Shft+Alt+8",FALSE,TRUE,TRUE},
	{'9',"Shft+Alt+9",FALSE,TRUE,TRUE},
	{VK_END,"Shft+Alt+End",FALSE,TRUE,TRUE},
	{VK_HOME,"Shft+Alt+Home",FALSE,TRUE,TRUE},
	{VK_LEFT,"Shft+Alt+←",FALSE,TRUE,TRUE},
	{VK_RIGHT,"Shft+Alt+→",FALSE,TRUE,TRUE},
	{VK_UP,"Shft+Alt+↑",FALSE,TRUE,TRUE},
	{VK_DOWN,"Shft+Alt+↓",FALSE,TRUE,TRUE},
	{VK_PRIOR,"Shft+Alt+PgUp",FALSE,TRUE,TRUE},
	{VK_NEXT,"Shft+Alt+PgDn",FALSE,TRUE,TRUE},
	{VK_INSERT,"Shft+Alt+Ins",FALSE,TRUE,TRUE},
	{VK_DELETE,"Shft+Alt+Del",FALSE,TRUE,TRUE},
	{VK_BACK,"Shft+Alt+Back",FALSE,TRUE,TRUE},
	{VK_RETURN,"Shft+Alt+Ret",FALSE,TRUE,TRUE},
	//Ｓｈｉｆｔ＋Ｃｔｒｌ＋Ａｌｔキー修飾あり
	{VK_F1,"Shft+Ctl+Alt+F1",TRUE,TRUE,TRUE},
	{VK_F2,"Shft+Ctl+Alt+F2",TRUE,TRUE,TRUE},
	{VK_F3,"Shft+Ctl+Alt+F3",TRUE,TRUE,TRUE},
	{VK_F4,"Shft+Ctl+Alt+F4",TRUE,TRUE,TRUE},
	{VK_F5,"Shft+Ctl+Alt+F5",TRUE,TRUE,TRUE},
	{VK_F6,"Shft+Ctl+Alt+F6",TRUE,TRUE,TRUE},
	{VK_F7,"Shft+Ctl+Alt+F7",TRUE,TRUE,TRUE},
	{VK_F8,"Shft+Ctl+Alt+F8",TRUE,TRUE,TRUE},
	{VK_F9,"Shft+Ctl+Alt+F9",TRUE,TRUE,TRUE},
	{VK_F10,"Shft+Ctl+Alt+F10",TRUE,TRUE,TRUE},
	{VK_F11,"Shft+Ctl+Alt+F11",TRUE,TRUE,TRUE},
	{VK_F12,"Shft+Ctl+Alt+F12",TRUE,TRUE,TRUE},
	{'0',"Shft+Ctl+Alt+0",TRUE,TRUE,TRUE},
	{'1',"Shft+Ctl+Alt+1",TRUE,TRUE,TRUE},
	{'2',"Shft+Ctl+Alt+2",TRUE,TRUE,TRUE},
	{'3',"Shft+Ctl+Alt+3",TRUE,TRUE,TRUE},
	{'4',"Shft+Ctl+Alt+4",TRUE,TRUE,TRUE},
	{'5',"Shft+Ctl+Alt+5",TRUE,TRUE,TRUE},
	{'6',"Shft+Ctl+Alt+6",TRUE,TRUE,TRUE},
	{'7',"Shft+Ctl+Alt+7",TRUE,TRUE,TRUE},
	{'8',"Shft+Ctl+Alt+8",TRUE,TRUE,TRUE},
	{'9',"Shft+Ctl+Alt+9",TRUE,TRUE,TRUE},
	{VK_END,"Shft+Ctl+Alt+End",TRUE,TRUE,TRUE},
	{VK_HOME,"Shft+Ctl+Alt+Home",TRUE,TRUE,TRUE},
	{VK_LEFT,"Shft+Ctl+Alt+←",TRUE,TRUE,TRUE},
	{VK_RIGHT,"Shft+Ctl+Alt+→",TRUE,TRUE,TRUE},
	{VK_UP,"Shft+Ctl+Alt+↑",TRUE,TRUE,TRUE},
	{VK_DOWN,"Shft+Ctl+Alt+↓",TRUE,TRUE,TRUE},
	{VK_PRIOR,"Shft+Ctl+Alt+PgUp",TRUE,TRUE,TRUE},
	{VK_NEXT,"Shft+Ctl+Alt+PgDn",TRUE,TRUE,TRUE},
	{VK_INSERT,"Shft+Ctl+Alt+Ins",TRUE,TRUE,TRUE},
	{VK_BACK,"Shft+Ctl+Alt+Back",TRUE,TRUE,TRUE},
	{VK_RETURN,"Shft+Ctl+Alt+Ret",TRUE,TRUE,TRUE},
	//終端
	{0,"",FALSE,FALSE,FALSE}
};

char* g_szFunc[] = 
{
	"ファイル系",
	"編集系",
	"検索系",
	"ジャンプ系",
	"表示系",
	"ツール系",
	"設定系",
	"ウインドウ系",
	"ヘルプ系",
	"その他系",
	""
};

#endif

#ifdef AFX_TARG_ENU

//グローバル変数
KEY_FUNC g_stKeyFunc[] =
{
	//ファイル系
	{"File",ID_FILE_NEW,"New","Create a new document." },
	{"File",ID_FILE_OPEN,"Open","Open an existing document." },
	{"File",ID_FILE_CLOSE,"Close","Close the active document." },
	{"File",ID_FILE_SAVECLOSE,"Save and close","Save the active document and close." },
	{"File",ID_FILE_SAVE,"Save","Save the active document."},
	{"File",ID_FILE_SAVE_AS,"Save as","Save the active document with a new name."},
	{"File",ID_FILE_ALLSAVE,"Save all files","Save the all documents."},
	{"File",ID_FILE_OPENONEXIT,"Open files when at exit","Open files when Xerxes opend at exit."},
	{"File",ID_HTTP_FILE_OPEN,"Open html file on web site","Download the specified html file from the web site and open it."},
	{"File",ID_FILE_REREAD,"Re-load","Reload the active document."},
	{"File",ID_FILE_PROPERTY,"Property","Display the information about the active document."},
	{"File",ID_FILE_OPENSAMENAME,"Open files of the same name","Open the files of same name."},
	{"File",ID_FILE_SHELLOPEN,"Open with the associated software","Open the active document with the associated software."},
	{"File",ID_FILE_MOVE,"Move","Move the active document to the specified directory."},
	{"File",ID_FILE_COPY,"Copy","Copy the active document to the specified directory."},
	{"File",ID_FILE_RENAME,"Rename","Rename the active document."},
	{"File",ID_FILE_DELETE,"Delete","Delete the active document."},
	{"File",ID_FILE_PRINT,"Print","Print the active document."},
	{"File",ID_FILE_PRINT_PREVIEW,"Print preview","Display full pages."},
	{"File",ID_FILE_PRINT_SETUP,"Print setup","Change the printer and printing options."},
	{"File",ID_FILE_MRU_FILE1,"Open the no 1 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE2,"Open the no 2 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE3,"Open the no 3 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE4,"Open the no 4 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE5,"Open the no 5 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE6,"Open the no 6 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE7,"Open the no 7 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE8,"Open the no 8 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE9,"Open the no 9 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE10,"Open the no 10 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE11,"Open the no 11 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE12,"Open the no 12 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE13,"Open the no 13 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE14,"Open the no 14 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE15,"Open the no 15 file recently used.","Open this document."},
	{"File",ID_FILE_MRU_FILE16,"Open the no 16 file recently used.","Open this document."},
	{"File",ID_ALLSAVE_EXIT,"Save all files and exit","Save the all documents and exit."},
	{"File",ID_APP_EXIT,"Exit","Quit the application."},
	//編集系
	{"Edit",ID_EDIT_UNDO,"Undo","Undo the last action."},
	{"Edit",ID_EDIT_REDO,"Redo","Redo the previously undone action."},
	{"Edit",ID_EDIT_CLEARUNDOBUF,"Undo/Redo buffer clearance","Clear Undo/Redo buffer."},
	{"Edit",ID_EDIT_ALLUNDO,"Undo all operations","All operation performed until now is undone."},
	{"Edit",ID_EDIT_ALLREDO,"Redo all operations","All operation performed until now is redone."},
	{"Edit",ID_EDIT_CUT,"Cut","Cut the selection and put it on the clipboard."},
	{"Edit",ID_EDIT_COPY,"Copy","Copy the selection and put it on the clipboard."},
	{"Edit",ID_EDIT_PASTE,"Paste","Insert clipboard contents."},
	{"Edit",ID_EDIT_DEL,"Delete","Delete the selection."},
	{"Edit",ID_EDIT_SELECTALL,"Select all","Select the entire document."},
	{"Edit",ID_EDIT_CLIPVIEW,"View clipboard","Display the contents of clipboard."},
	{"Edit",ID_EDIT_BROWSEURL,"Browse URL","Browse the URL at caret."},
	{"Edit",ID_EDIT_EXECMAILER,"Start a mailer","Execute mailer with mail address at caret."},
	{"Edit",ID_EDIT_SETREADONLY,"Make the ban on writing","Change the file attribute to read only."},
	{"Edit",ID_EDIT_UNSETREADONLY,"Cancel the ban on writing","Change the file attribute to write ok."},
	{"Edit",ID_EDIT_INSDAY,"Insert date","Insert date at caret position."},
	{"Edit",ID_EDIT_INSTIME,"Insert time","Insert time at caret position."},
	{"Edit",ID_EDIT_CRLF,"DOS/Windows  CR+LF","Convert new-line code of the active document to CRLF."},
	{"Edit",ID_EDIT_LF,"UNIX  LF","Convert new-line code of the active document to LF."},
	{"Edit",ID_EDIT_CR,"Macintosh  CR","Convert new-line code of the active document to CR."},
	{"Edit",ID_EDIT_CODE2EUC,"EUC code","Convert character code of the active document to EUC code."},
	{"Edit",ID_EDIT_CODE2SJIS,"Shift-JIS code","Convert character code of the active document to Shift-JIS code."},
	{"Edit",ID_EDIT_CODE2JIS,"JIS code","Convert character code of the active document to JIS code."},
	{"Edit",ID_EDIT_TAB2SPACE,"Tab -> Half-size space","Convert tab to half-size space in selection."},
	{"Edit",ID_EDIT_SPACE2TAB,"Half-size space -> Tab","Convert half-size space to tab in selection."},
	{"Edit",ID_EDIT_SPACE_ZEN2HAN,"Space Full-size -> Half-size",
			"Convert full-size space to half-size space in selection."},
	{"Edit",ID_EDIT_SPACE_HAN2ZEN,"Space Half-size -> Full-size",
			"Convert half-size space to full-size space in selection."},
	{"Edit",ID_EDIT_KATAKANA_HAN2ZEN,"Katakana Half-size -> Full-size",
			"Convert half-size katakana to full-size katakana."},
	{"Edit",ID_EDIT_KATAKANA_ZEN2HAN,"Katakana Full-size -> Half-size",
			"Convert full-size katakana to half-size katakana."},
	{"Edit",ID_EDIT_ALNUM_HAN2ZEN,"Alphanumeric character Half-size -> Full-size",
			"Convert half-size alphanumeric character to full-size in selection."},
	{"Edit",ID_EDIT_ALNUM_ZEN2HAN,"Alphanumeric character Full-size -> Half-size",
			"Convert full-size alphanumeric character to half-size in selection."},
	{"Edit",ID_EDIT_AL2UPPER,"Alphabetic character -> Capital letter",
			"Convert half-size alpabet to upper case in selection."},
	{"Edit",ID_EDIT_AL2LOWER,"Alphabetic character -> Small letter",
			"Convert half-size alphabet to lower case in selection."},
	{"Edit",ID_EDIT_DELTOPSPACES,"Delete all spaces and tabs in the head",
			"Delete all spaces and tabs at head in selection."},
	{"Edit",ID_EDIT_INSTAB,"Insert a tab","Insert a tab into the selection."},
	{"Edit",ID_EDIT_DELTAB,"Delete a tab","Delete a tab in the selection."},
	{"Edit",ID_EDIT_INSCPPCOMMENT,"Insert C/C++ line comment.","Insert C/C++ line comment in the selection."},
	{"Edit",ID_EDIT_DELCPPCOMMENT,"Delete C/C++ line comment.","Delete C/C++ line comment in the top of selection."},
	{"Edit",ID_EDIT_INSVBCOMMENT,"Insert VB line comment.","Insert VB line comment in the selection."},
	{"Edit",ID_EDIT_DELVBCOMMENT,"Delete VB line comment.","Delete VB line comment in the top of selection."},
	{"Edit",ID_EDIT_INSASMCOMMENT,"Insert assembler line comment.","Insert assembler line comment in the selection."},
	{"Edit",ID_EDIT_DELASMCOMMENT,"Delete assembler line comment.","Delete assembler line comment in the top of selection."},
	{"Edit",ID_EDIT_INSQUOTE,"Insert a quotation mark","Insert a quotation mark in the selection."},
	{"Edit",ID_EDIT_DELQUOTE,"Delete a quotation mark","Delete a quotation mark in the top of selection"},
	//検索系
	{"Find",ID_EDIT_FIND,"Find the specified text.","Find the specfied text."},
	{"Find",ID_EDIT_FINDCONTINUE,"Continue to find downword.","Continue to find text downword."},
	{"Find",ID_EDIT_FINDREVCONTINUE,"Continue to find upword.","Continue to find text upword."},
	{"Find",ID_EDIT_INCRIMENTALSEARCH,"Incremental search.","Start/End incremental search."},
	{"Find",ID_EDIT_REPLACE,"Replace the specified text.","Replace the specified text with a different text."},
	{"Find",ID_EDIT_GREP,"Grep","Search the specified text from files."},
	{"Find",ID_EDIT_FILECOMPARE,"File comparison","Compare the two files and search different lines."},
	{"Find",ID_EDIT_FCOMP_TABEQUAL2SPACE,"White spaces are not distinguished.","White spaces are not distinguished at the time of file comparison."},
	{"Find",ID_EDIT_FCOMP_ZENEQUAL2HAN,"Full size and half size are not distinguished.","Full size and half size are not distinguished at the time of file comparison."},
	{"Find",ID_EDIT_FCOMP_ALPHABETBIGANDSMALL,"The capital letter and small letter are not distinguished.","The capital letter and small letter are not distinguished at the time of file comparison."},
	{"Find",ID_EDIT_NEXTDIFF,"Jump to the different line downword.","Jump to the different line downword."},
	{"Find",ID_EDIT_PREVDIFF,"Jump to the different line upword.","Jump to the different line upword."},
	{"Find",ID_EDIT_FILERECOMPARE,"File Re-comparison","Re-Compare the current two files and search different lines."},
	{"Find",ID_EDIT_DIRCOMPARE,"Directory comparison.","Compare the two directories and search different files."},
	{"Find",ID_EDIT_DIRCMP_SYOSAI,"Compare different files in detail.","Compare the different files."},
	//ジャンプ系
	{"Jump",ID_EDIT_JUMP2TOP,"Jump to a head line.","Jump to a head line."},
	{"Jump",ID_EDIT_JUMP2BOTTOM,"Jump to a last line.","Jump to a last line."},
	{"Jump",ID_EDIT_JUMP2LINE,"Jump to a specified line.","Jump to a specified line."},
	{"Jump",ID_EDIT_JUMP2TOPSELECT,"Jump to a head line with selection.","Jump to a head line with selection."},
	{"Jump",ID_EDIT_JUMP2BOTTOMSELECT,"Jump to last line with selection.","Jump to a last line with selection."},
	{"Jump",ID_PARENTHESIS,"Jump to a corresponding parenthesis.","Jump to a corresponding parenthesis."},
	{"Jump",ID_PARENTHESIS_SELECT,"Jump to a corresponding parenthesis with selection.",
			"Jump to a corresponding parenthesis with selection"},
	{"Jump",ID_EDIT_TAGJUMP,"Tag jump","Get tag information and open the file."},
	{"Jump",ID_JUMP_SETMARK,"Mark the current line.","Mark the current line."},
	{"Jump",ID_JUMP_DELMARK,"Mark release the current line.","Mark release the current line."},
	{"Jump",ID_JUMP_ALLDELMARK,"Mark release all line","Mark release all line."},
	{"Jump",ID_JUMP_NEXTMARK,"Jump to the marked line downword.",
			"Jump to the marked line downword."},
	{"Jump",ID_JUMP_PREVMARK,"Jump to the marked line upword.",
			"Jump to the marked line upword."},
	{"Jump",ID_JUMP_MARKLIST,"Display the marked line list.","Display the marked line list"},
	//表示系
	{"View",ID_VIEW_TOOLBAR,"Standard tool bar","Show or hide the standard tool bar."},
	{"View",ID_VIEW_TOOLBAR_EDIT,"Edit related tool bar","Show or hide the edit related tool bar."},
	{"View",ID_VIEW_TOOLBAR_FIND,"Find related tool bar","Show or hide the find related tool bar."},
	{"View",ID_VIEW_TOOLBAR_JMP,"Jump related tool bar","Show or hide the jump related tool bar."},
	{"View",ID_VIEW_TOOLBAR_TOOLS,"Tool related tool bar","Show or hide the tool related tool bar."},
	{"View",ID_VIEW_TOOLBAR_WND,"Window related tool bar","Show or hide the window related tool bar."},
	{"View",ID_VIEW_STATUS_BAR,"Status bar","Show or hide the status bar."},
	{"View",ID_VIEW_REDRAW,"Reflesh","Reflesh the active window."},
	{"View",ID_VIEW_LINENO,"Display line no","Display line no"},
	{"View",ID_VIEW_RULER,"Display ruler","Display ruler"},
	{"View",ID_VIEW_CRLF,"Display new-line code","Display new-line code"},
	{"View",ID_VIEW_TAB,"Display tab","Display tab"},
	{"View",ID_VIEW_ZENKAKUSPACE,"Display full-size space","Display full-size space"},
	{"View",ID_VIEW_UNDERLINE,"Display underline","Display underline"},
	{"View",ID_VIEW_EOF,"Display the end of file mark.","Display the end of file mark."},
	{"View",ID_VIEW_CARET_IBEAM,"Caret form : I beam","Change the caret form to I beam."},
	{"View",ID_VIEW_CARET_SQUARE,"Caret form : square","Change the caret form to square."},
	{"View",ID_VIEW_TAB_2,"2 tab","Tab size : 2"},
	{"View",ID_VIEW_TAB_4,"4 tab","Tab size : 4"},
	{"View",ID_VIEW_TAB_8,"8 tab","Tab size : 8"},
	//ツール系
	{"Tool",ID_FILE_SENDMAIL,"Send mail","Send the active document as mail."},
	{"Tool",ID_FILE_MAILLIST,"POP3 server mail list","A received mail list is displayed on a POP3 server."},
	{"Tool",ID_EDIT_ASCIIDUMP,"Dumping in a ASCII code","Dump the contents of the active document in ASCII code."},
	{"Tool",ID_EDIT_SJISDUMP,"Dumping in a Shift-JIS code","Dump the contents of the active document in Shift-JIS code."},
	{"Tool",ID_EDIT_CODECONV,"Character code conversion",
			"Convert character code of files to Shift-JIS, EUC, JIS."},
	{"Tool",ID_EDIT_KAIGYOCONV,"New-line code conversion",
			"Convert new-line code of files to CRLF, LF, CR"},
	{"Tool",ID_EDIT_WORDCOUNT,"WORD count","Count words in files"},
	{"Tool",ID_EDIT_FILESEARCH,"File search","Search files which matches the specified condition."},
	{"Tool",ID_EDIT_FILETOUCH,"File touch","Change the update time of files."},
	{"Tool",ID_EDIT_SOURCEARRANGE,"Arrange C/C++ Source","Arrange indents and parenthesis of C/C++ source file."},
	{"Tool",ID_SECURITY_ENCRIPT,"File encryption","File encryption"},
	{"Tool",ID_SECURITY_DECRIPT,"File decryption","File decryption"},
	{"Tool",ID_EDIT_UUENCODE,"Uuencode","Uuencode the specified file"},
	{"Tool",ID_EDIT_BASE64ENCODE,"Base64 encoding","Base64 encode the specified file."},
	{"Tool",ID_EDIT_QUOTEDENCODE,"Quoted-printable encoding","Quoted-printable encode the specified file."},
	{"Tool",ID_EDIT_UUDECODE,"Uudecode","Uudecode the selection and save to a file."},
	{"Tool",ID_EDIT_BASE64DECODE,"Base64 decoding","Base64 decode the selection and save to a file."},
	{"Tool",ID_EDIT_QUOTEDDECODE,"Quoted-printable decoding","Quoted-printable deocde the selection and save to a file."},
	{"Tool",ID_TOOL_OPE_STARTENDRECORD,"Recording key operations","Start/End to record key operations."},
	{"Tool",ID_TOOL_OPE_DO,"Executing key operations","Execute the recorded key operations."},
	{"Tool",ID_TOOL_OPE_STEPDO_NEXT,"Execute the next key operation","Execute the next key operation."},
	{"Tool",ID_TOOL_OPE_STEPDO_END,"Stop the execution of key operation","Stop the execution of key operation"},
	{"Tool",ID_TOOL_OPE_SAVE,"Save key operation to a file.","Save the recorded key operations to a file."},
	{"Tool",ID_TOOL_OPE_OPEN,"Read key operation from a file.","Read key operations from a file."},
	{"Tool",ID_TOOL_OPE_DISP,"Display key operations","Display the recorded key operation."},
	//設定系
	{"Settings",ID_SETTINGS,"Settings","Settings"},
	{"Settings",ID_CUSTOMIZE_TOOLBAR,"Customize Standard tool bar",
			"The button row of a standard tool bar is customized."},
	{"Settings",ID_CUSTOMIZE_TOOLBAREDIT,"Customize Edit related tool bar",
			"The button row of a edit related tool bar is customized."},
	{"Settings",ID_CUSTOMIZE_TOOLBARFIND,"Customize Find related tool bar",
			"The button row of a find related tool bar is customized."},
	{"Settings",ID_CUSTOMIZE_TOOLBARJMP,"Customize Jump related tool bar",
			"The button row of a jump related tool bar is customized."},
	{"Settings",ID_CUSTOMIZE_TOOLBARTOOLS,"Customize Tool related tool bar",
			"The button row of a tool related tool bar is customized."},
	{"Settings",ID_CUSTOMIZE_TOOLBARWND,"Customize Window related tool bar",
			"The button row of a window related tool bar is customized."},
	//ウインドウ系
	{"Window",ID_WINDOW_NEW,"New window","Open another window for the active document."},
	{"Window",ID_WINDOW_SPLIT,"Split window","Split the active window into panes."},
	{"Window",ID_WINDOW_ARRANGE,"Arrange icons","Arrange icons at the bottom of the window."},
	{"Window",ID_WINDOW_MINIMIZE,"Minimize","Reduce the window to an icon."},
	{"Window",ID_WINDOW_MAXIMIZE,"Maximize","Enlarge the window to full size."},
	{"Window",ID_WINDOW_RESTORE,"Restore","Restore the window to normal size."},
	{"Window",ID_WND_NEXT,"Next window","Switch to the next document window."},
	{"Window",ID_WND_PREV,"Prev window","Switch to the previous document window."},
	{"Window",ID_NEXT_PANE,"Next pane","Switch to the next window pane."},
	{"Window",ID_PREV_PANE,"Prev pane","Switch back to the previous window pane."},
	{"Window",ID_WINDOW_CASCADE,"Cascade","Arrange windows so they overlap."},
	{"Window",ID_WINDOW_TILE_HORZ,"Arrange up and down","Arrange windows as non-overlapping tiles."},
	{"Window",ID_WINDOW_TILE_VERT,"Arrange right and left","Arrange windows as non-overlapping tiles."},
	{"Window",ID_WINDOW_CLOSE,"Close","Close the active window."},
	{"Window",ID_WINDOW_ALLCLOSE,"Close all","Close the all windows."},
	//ヘルプ系
	{"Help",ID_HELP_CONTENT,"Table of contents","Display the table of contents."},
	{"Help",ID_HELP_CONTENT2,"HTML Help table of contents","Display table of contents of HTML help."},
	{"Help",ID_APP_ABOUT,"Version information","Display program information,version number and copyright."},
	{"Help",ID_HELP_LICENSE,"License registration","Input user information, register user ID."},
	//その他系
	{"others",ID_WORDSKIP2LEFT,"Word skip to left","Word skip the caret to left."},
	{"others",ID_WORDSKIP2RIGHT,"Word skip to right","Word skip the caret to right."},
	{"others",ID_WORDSELECT2LEFT,"Word select to left","Word select the caret to left."},
	{"others",ID_WORDSELECT2RIGHT,"Word select to right","Word select the caret to right."},
	{"",0,"",""}
};
		
KEY g_stKeys[] = 
{
	//キー修飾なし
	{VK_F1,"F1",FALSE,FALSE,FALSE},
	{VK_F2,"F2",FALSE,FALSE,FALSE},
	{VK_F3,"F3",FALSE,FALSE,FALSE},
	{VK_F4,"F4",FALSE,FALSE,FALSE},
	{VK_F5,"F5",FALSE,FALSE,FALSE},
	{VK_F6,"F6",FALSE,FALSE,FALSE},
	{VK_F7,"F7",FALSE,FALSE,FALSE},
	{VK_F8,"F8",FALSE,FALSE,FALSE},
	{VK_F9,"F9",FALSE,FALSE,FALSE},
	{VK_F10,"F10",FALSE,FALSE,FALSE},
	{VK_F11,"F11",FALSE,FALSE,FALSE},
	{VK_F12,"F12",FALSE,FALSE,FALSE},
	//Ａｌｔキー修飾あり
	{VK_F1,"Alt+F1",FALSE,FALSE,TRUE},
	{VK_F2,"Alt+F2",FALSE,FALSE,TRUE},
	{VK_F3,"Alt+F3",FALSE,FALSE,TRUE},
	{VK_F4,"Alt+F4",FALSE,FALSE,TRUE},
	{VK_F5,"Alt+F5",FALSE,FALSE,TRUE},
	{VK_F6,"Alt+F6",FALSE,FALSE,TRUE},
	{VK_F7,"Alt+F7",FALSE,FALSE,TRUE},
	{VK_F8,"Alt+F8",FALSE,FALSE,TRUE},
	{VK_F9,"Alt+F9",FALSE,FALSE,TRUE},
	{VK_F10,"Alt+F10",FALSE,FALSE,TRUE},
	{VK_F11,"Alt+F11",FALSE,FALSE,TRUE},
	{VK_F12,"Alt+F12",FALSE,FALSE,TRUE},
	{'0',"Alt+0",FALSE,FALSE,TRUE},
	{'1',"Alt+1",FALSE,FALSE,TRUE},
	{'2',"Alt+2",FALSE,FALSE,TRUE},
	{'3',"Alt+3",FALSE,FALSE,TRUE},
	{'4',"Alt+4",FALSE,FALSE,TRUE},
	{'5',"Alt+5",FALSE,FALSE,TRUE},
	{'6',"Alt+6",FALSE,FALSE,TRUE},
	{'7',"Alt+7",FALSE,FALSE,TRUE},
	{'8',"Alt+8",FALSE,FALSE,TRUE},
	{'9',"Alt+9",FALSE,FALSE,TRUE},
	{VK_END,"Alt+End",FALSE,FALSE,TRUE},
	{VK_HOME,"Alt+Home",FALSE,FALSE,TRUE},
	{VK_LEFT,"Alt+←",FALSE,FALSE,TRUE},
	{VK_RIGHT,"Alt+→",FALSE,FALSE,TRUE},
	{VK_UP,"Alt+↑",FALSE,FALSE,TRUE},
	{VK_DOWN,"Alt+↓",FALSE,FALSE,TRUE},
	{VK_PRIOR,"Alt+PgUp",FALSE,FALSE,TRUE},
	{VK_NEXT,"Alt+PgDn",FALSE,FALSE,TRUE},
	{VK_INSERT,"Alt+Ins",FALSE,FALSE,TRUE},
	{VK_DELETE,"Alt+Del",FALSE,FALSE,TRUE},
	{VK_BACK,"Alt+Back",FALSE,FALSE,TRUE},
	{VK_RETURN,"Alt+Ret",FALSE,FALSE,TRUE},
	//Ｓｈｉｆｔキー修飾あり
	{VK_F1,"Shft+F1",FALSE,TRUE,FALSE},
	{VK_F2,"Shft+F2",FALSE,TRUE,FALSE},
	{VK_F3,"Shft+F3",FALSE,TRUE,FALSE},
	{VK_F4,"Shft+F4",FALSE,TRUE,FALSE},
	{VK_F5,"Shft+F5",FALSE,TRUE,FALSE},
	{VK_F6,"Shft+F6",FALSE,TRUE,FALSE},
	{VK_F7,"Shft+F7",FALSE,TRUE,FALSE},
	{VK_F8,"Shft+F8",FALSE,TRUE,FALSE},
	{VK_F9,"Shft+F9",FALSE,TRUE,FALSE},
	{VK_F10,"Shft+F10",FALSE,TRUE,FALSE},
	{VK_F11,"Shft+F11",FALSE,TRUE,FALSE},
	{VK_F12,"Shft+F12",FALSE,TRUE,FALSE},
	{VK_INSERT,"Shft+Ins",FALSE,TRUE,FALSE},
	{VK_DELETE,"Shft+Del",FALSE,TRUE,FALSE},
	{VK_BACK,"Shft+Back",FALSE,TRUE,FALSE},
	{VK_RETURN,"Shft+Ret",FALSE,TRUE,FALSE},
	//Ｃｔｒｌキー修飾あり
	{VK_F1,"Ctl+F1",TRUE,FALSE,FALSE},
	{VK_F2,"Ctl+F2",TRUE,FALSE,FALSE},
	{VK_F3,"Ctl+F3",TRUE,FALSE,FALSE},
	{VK_F4,"Ctl+F4",TRUE,FALSE,FALSE},
	{VK_F5,"Ctl+F5",TRUE,FALSE,FALSE},
	{VK_F6,"Ctl+F6",TRUE,FALSE,FALSE},
	{VK_F7,"Ctl+F7",TRUE,FALSE,FALSE},
	{VK_F8,"Ctl+F8",TRUE,FALSE,FALSE},
	{VK_F9,"Ctl+F9",TRUE,FALSE,FALSE},
	{VK_F10,"Ctl+F10",TRUE,FALSE,FALSE},
	{VK_F11,"Ctl+F11",TRUE,FALSE,FALSE},
	{VK_F12,"Ctl+F12",TRUE,FALSE,FALSE},
	{'A',"Ctl+A",TRUE,FALSE,FALSE},
	{'B',"Ctl+B",TRUE,FALSE,FALSE},
	{'C',"Ctl+C",TRUE,FALSE,FALSE},
	{'D',"Ctl+D",TRUE,FALSE,FALSE},
	{'E',"Ctl+E",TRUE,FALSE,FALSE},
	{'F',"Ctl+F",TRUE,FALSE,FALSE},
	{'G',"Ctl+G",TRUE,FALSE,FALSE},
	{'H',"Ctl+H",TRUE,FALSE,FALSE},
	{'I',"Ctl+I",TRUE,FALSE,FALSE},
	{'J',"Ctl+J",TRUE,FALSE,FALSE},
	{'K',"Ctl+K",TRUE,FALSE,FALSE},
	{'L',"Ctl+L",TRUE,FALSE,FALSE},
	{'M',"Ctl+M",TRUE,FALSE,FALSE},
	{'N',"Ctl+N",TRUE,FALSE,FALSE},
	{'O',"Ctl+O",TRUE,FALSE,FALSE},
	{'P',"Ctl+P",TRUE,FALSE,FALSE},
	{'Q',"Ctl+Q",TRUE,FALSE,FALSE},
	{'R',"Ctl+R",TRUE,FALSE,FALSE},
	{'S',"Ctl+S",TRUE,FALSE,FALSE},
	{'T',"Ctl+T",TRUE,FALSE,FALSE},
	{'U',"Ctl+U",TRUE,FALSE,FALSE},
	{'V',"Ctl+V",TRUE,FALSE,FALSE},
	{'W',"Ctl+W",TRUE,FALSE,FALSE},
	{'X',"Ctl+X",TRUE,FALSE,FALSE},
	{'Y',"Ctl+Y",TRUE,FALSE,FALSE},
	{'Z',"Ctl+Z",TRUE,FALSE,FALSE},
	{'0',"Ctl+0",TRUE,FALSE,FALSE},
	{'1',"Ctl+1",TRUE,FALSE,FALSE},
	{'2',"Ctl+2",TRUE,FALSE,FALSE},
	{'3',"Ctl+3",TRUE,FALSE,FALSE},
	{'4',"Ctl+4",TRUE,FALSE,FALSE},
	{'5',"Ctl+5",TRUE,FALSE,FALSE},
	{'6',"Ctl+6",TRUE,FALSE,FALSE},
	{'7',"Ctl+7",TRUE,FALSE,FALSE},
	{'8',"Ctl+8",TRUE,FALSE,FALSE},
	{'9',"Ctl+9",TRUE,FALSE,FALSE},
	{VK_END,"Ctl+End",TRUE,FALSE,FALSE},
	{VK_HOME,"Ctl+Home",TRUE,FALSE,FALSE},
	{VK_LEFT,"Ctl+←",TRUE,FALSE,FALSE},
	{VK_RIGHT,"Ctl+→",TRUE,FALSE,FALSE},
	{VK_UP,"Ctl+↑",TRUE,FALSE,FALSE},
	{VK_DOWN,"Ctl+↓",TRUE,FALSE,FALSE},
	{VK_PRIOR,"Ctl+PgUp",TRUE,FALSE,FALSE},
	{VK_NEXT,"Ctl+PgDn",TRUE,FALSE,FALSE},
	{VK_INSERT,"Ctl+Ins",TRUE,FALSE,FALSE},
	{VK_DELETE,"Ctl+Del",TRUE,FALSE,FALSE},
	{VK_BACK,"Ctl+Back",TRUE,FALSE,FALSE},
	{VK_RETURN,"Ctl+Ret",TRUE,FALSE,FALSE},
	//ＳｈｉｆｔＣｔｒｌキー修飾あり
	{VK_F1,"Shft+Ctl+F1",TRUE,TRUE,FALSE},
	{VK_F2,"Shft+Ctl+F2",TRUE,TRUE,FALSE},
	{VK_F3,"Shft+Ctl+F3",TRUE,TRUE,FALSE},
	{VK_F4,"Shft+Ctl+F4",TRUE,TRUE,FALSE},
	{VK_F5,"Shft+Ctl+F5",TRUE,TRUE,FALSE},
	{VK_F6,"Shft+Ctl+F6",TRUE,TRUE,FALSE},
	{VK_F7,"Shft+Ctl+F7",TRUE,TRUE,FALSE},
	{VK_F8,"Shft+Ctl+F8",TRUE,TRUE,FALSE},
	{VK_F9,"Shft+Ctl+F9",TRUE,TRUE,FALSE},
	{VK_F10,"Shft+Ctl+F10",TRUE,TRUE,FALSE},
	{VK_F11,"Shft+Ctl+F11",TRUE,TRUE,FALSE},
	{VK_F12,"Shft+Ctl+F12",TRUE,TRUE,FALSE},
	{'A',"Shft+Ctl+A",TRUE,TRUE,FALSE},
	{'B',"Shft+Ctl+B",TRUE,TRUE,FALSE},
	{'C',"Shft+Ctl+C",TRUE,TRUE,FALSE},
	{'D',"Shft+Ctl+D",TRUE,TRUE,FALSE},
	{'E',"Shft+Ctl+E",TRUE,TRUE,FALSE},
	{'F',"Shft+Ctl+F",TRUE,TRUE,FALSE},
	{'G',"Shft+Ctl+G",TRUE,TRUE,FALSE},
	{'H',"Shft+Ctl+H",TRUE,TRUE,FALSE},
	{'I',"Shft+Ctl+I",TRUE,TRUE,FALSE},
	{'J',"Shft+Ctl+J",TRUE,TRUE,FALSE},
	{'K',"Shft+Ctl+K",TRUE,TRUE,FALSE},
	{'L',"Shft+Ctl+L",TRUE,TRUE,FALSE},
	{'M',"Shft+Ctl+M",TRUE,TRUE,FALSE},
	{'N',"Shft+Ctl+N",TRUE,TRUE,FALSE},
	{'O',"Shft+Ctl+O",TRUE,TRUE,FALSE},
	{'P',"Shft+Ctl+P",TRUE,TRUE,FALSE},
	{'Q',"Shft+Ctl+Q",TRUE,TRUE,FALSE},
	{'R',"Shft+Ctl+R",TRUE,TRUE,FALSE},
	{'S',"Shft+Ctl+S",TRUE,TRUE,FALSE},
	{'T',"Shft+Ctl+T",TRUE,TRUE,FALSE},
	{'U',"Shft+Ctl+U",TRUE,TRUE,FALSE},
	{'V',"Shft+Ctl+V",TRUE,TRUE,FALSE},
	{'W',"Shft+Ctl+W",TRUE,TRUE,FALSE},
	{'X',"Shft+Ctl+X",TRUE,TRUE,FALSE},
	{'Y',"Shft+Ctl+Y",TRUE,TRUE,FALSE},
	{'Z',"Shft+Ctl+Z",TRUE,TRUE,FALSE},
	{'0',"Shft+Ctl+0",TRUE,TRUE,FALSE},
	{'1',"Shft+Ctl+1",TRUE,TRUE,FALSE},
	{'2',"Shft+Ctl+2",TRUE,TRUE,FALSE},
	{'3',"Shft+Ctl+3",TRUE,TRUE,FALSE},
	{'4',"Shft+Ctl+4",TRUE,TRUE,FALSE},
	{'5',"Shft+Ctl+5",TRUE,TRUE,FALSE},
	{'6',"Shft+Ctl+6",TRUE,TRUE,FALSE},
	{'7',"Shft+Ctl+7",TRUE,TRUE,FALSE},
	{'8',"Shft+Ctl+8",TRUE,TRUE,FALSE},
	{'9',"Shft+Ctl+9",TRUE,TRUE,FALSE},
	{VK_END,"Shft+Ctl+End",TRUE,TRUE,FALSE},
	{VK_HOME,"Shft+Ctl+Home",TRUE,TRUE,FALSE},
	{VK_LEFT,"Shft+Ctl+←",TRUE,TRUE,FALSE},
	{VK_RIGHT,"Shft+Ctl+→",TRUE,TRUE,FALSE},
	{VK_UP,"Shft+Ctl+↑",TRUE,TRUE,FALSE},
	{VK_DOWN,"Shft+Ctl+↓",TRUE,TRUE,FALSE},
	{VK_PRIOR,"Shft+Ctl+PgUp",TRUE,TRUE,FALSE},
	{VK_NEXT,"Shft+Ctl+PgDn",TRUE,TRUE,FALSE},
	{VK_INSERT,"Shft+Ctl+Ins",TRUE,TRUE,FALSE},
	{VK_DELETE,"Shft+Ctl+Del",TRUE,TRUE,FALSE},
	{VK_BACK,"Shft+Ctl+Back",TRUE,TRUE,FALSE},
	{VK_RETURN,"Shft+Ctl+Ret",TRUE,TRUE,FALSE},
	//Ｃｔｒｌ＋Ａｌｔキー修飾あり
	{VK_F1,"Ctl+Alt+F1",TRUE,FALSE,TRUE},
	{VK_F2,"Ctl+Alt+F2",TRUE,FALSE,TRUE},
	{VK_F3,"Ctl+Alt+F3",TRUE,FALSE,TRUE},
	{VK_F4,"Ctl+Alt+F4",TRUE,FALSE,TRUE},
	{VK_F5,"Ctl+Alt+F5",TRUE,FALSE,TRUE},
	{VK_F6,"Ctl+Alt+F6",TRUE,FALSE,TRUE},
	{VK_F7,"Ctl+Alt+F7",TRUE,FALSE,TRUE},
	{VK_F8,"Ctl+Alt+F8",TRUE,FALSE,TRUE},
	{VK_F9,"Ctl+Alt+F9",TRUE,FALSE,TRUE},
	{VK_F10,"Ctl+Alt+F10",TRUE,FALSE,TRUE},
	{VK_F11,"Ctl+Alt+F11",TRUE,FALSE,TRUE},
	{VK_F12,"Ctl+Alt+F12",TRUE,FALSE,TRUE},
	{'0',"Ctl+Alt+0",TRUE,FALSE,TRUE},
	{'1',"Ctl+Alt+1",TRUE,FALSE,TRUE},
	{'2',"Ctl+Alt+2",TRUE,FALSE,TRUE},
	{'3',"Ctl+Alt+3",TRUE,FALSE,TRUE},
	{'4',"Ctl+Alt+4",TRUE,FALSE,TRUE},
	{'5',"Ctl+Alt+5",TRUE,FALSE,TRUE},
	{'6',"Ctl+Alt+6",TRUE,FALSE,TRUE},
	{'7',"Ctl+Alt+7",TRUE,FALSE,TRUE},
	{'8',"Ctl+Alt+8",TRUE,FALSE,TRUE},
	{'9',"Ctl+Alt+9",TRUE,FALSE,TRUE},
	{VK_END,"Ctl+Alt+End",TRUE,FALSE,TRUE},
	{VK_HOME,"Ctl+Alt+Home",TRUE,FALSE,TRUE},
	{VK_LEFT,"Ctl+Alt+←",TRUE,FALSE,TRUE},
	{VK_RIGHT,"Ctl+Alt+→",TRUE,FALSE,TRUE},
	{VK_UP,"Ctl+Alt+↑",TRUE,FALSE,TRUE},
	{VK_DOWN,"Ctl+Alt+↓",TRUE,FALSE,TRUE},
	{VK_PRIOR,"Ctl+Alt+PgUp",TRUE,FALSE,TRUE},
	{VK_NEXT,"Ctl+Alt+PgDn",TRUE,FALSE,TRUE},
	{VK_INSERT,"Ctl+Alt+Ins",TRUE,FALSE,TRUE},
	{VK_BACK,"Ctl+Alt+Back",TRUE,FALSE,TRUE},
	{VK_RETURN,"Ctl+Alt+Ret",TRUE,FALSE,TRUE},
	//Ｓｈｉｆｔ＋Ａｌｔキー修飾あり
	{VK_F1,"Shft+Alt+F1",FALSE,TRUE,TRUE},
	{VK_F2,"Shft+Alt+F2",FALSE,TRUE,TRUE},
	{VK_F3,"Shft+Alt+F3",FALSE,TRUE,TRUE},
	{VK_F4,"Shft+Alt+F4",FALSE,TRUE,TRUE},
	{VK_F5,"Shft+Alt+F5",FALSE,TRUE,TRUE},
	{VK_F6,"Shft+Alt+F6",FALSE,TRUE,TRUE},
	{VK_F7,"Shft+Alt+F7",FALSE,TRUE,TRUE},
	{VK_F8,"Shft+Alt+F8",FALSE,TRUE,TRUE},
	{VK_F9,"Shft+Alt+F9",FALSE,TRUE,TRUE},
	{VK_F10,"Shft+Alt+F10",FALSE,TRUE,TRUE},
	{VK_F11,"Shft+Alt+F11",FALSE,TRUE,TRUE},
	{VK_F12,"Shft+Alt+F12",FALSE,TRUE,TRUE},
	{'0',"Shft+Alt+0",FALSE,TRUE,TRUE},
	{'1',"Shft+Alt+1",FALSE,TRUE,TRUE},
	{'2',"Shft+Alt+2",FALSE,TRUE,TRUE},
	{'3',"Shft+Alt+3",FALSE,TRUE,TRUE},
	{'4',"Shft+Alt+4",FALSE,TRUE,TRUE},
	{'5',"Shft+Alt+5",FALSE,TRUE,TRUE},
	{'6',"Shft+Alt+6",FALSE,TRUE,TRUE},
	{'7',"Shft+Alt+7",FALSE,TRUE,TRUE},
	{'8',"Shft+Alt+8",FALSE,TRUE,TRUE},
	{'9',"Shft+Alt+9",FALSE,TRUE,TRUE},
	{VK_END,"Shft+Alt+End",FALSE,TRUE,TRUE},
	{VK_HOME,"Shft+Alt+Home",FALSE,TRUE,TRUE},
	{VK_LEFT,"Shft+Alt+←",FALSE,TRUE,TRUE},
	{VK_RIGHT,"Shft+Alt+→",FALSE,TRUE,TRUE},
	{VK_UP,"Shft+Alt+↑",FALSE,TRUE,TRUE},
	{VK_DOWN,"Shft+Alt+↓",FALSE,TRUE,TRUE},
	{VK_PRIOR,"Shft+Alt+PgUp",FALSE,TRUE,TRUE},
	{VK_NEXT,"Shft+Alt+PgDn",FALSE,TRUE,TRUE},
	{VK_INSERT,"Shft+Alt+Ins",FALSE,TRUE,TRUE},
	{VK_DELETE,"Shft+Alt+Del",FALSE,TRUE,TRUE},
	{VK_BACK,"Shft+Alt+Back",FALSE,TRUE,TRUE},
	{VK_RETURN,"Shft+Alt+Ret",FALSE,TRUE,TRUE},
	//Ｓｈｉｆｔ＋Ｃｔｒｌ＋Ａｌｔキー修飾あり
	{VK_F1,"Shft+Ctl+Alt+F1",TRUE,TRUE,TRUE},
	{VK_F2,"Shft+Ctl+Alt+F2",TRUE,TRUE,TRUE},
	{VK_F3,"Shft+Ctl+Alt+F3",TRUE,TRUE,TRUE},
	{VK_F4,"Shft+Ctl+Alt+F4",TRUE,TRUE,TRUE},
	{VK_F5,"Shft+Ctl+Alt+F5",TRUE,TRUE,TRUE},
	{VK_F6,"Shft+Ctl+Alt+F6",TRUE,TRUE,TRUE},
	{VK_F7,"Shft+Ctl+Alt+F7",TRUE,TRUE,TRUE},
	{VK_F8,"Shft+Ctl+Alt+F8",TRUE,TRUE,TRUE},
	{VK_F9,"Shft+Ctl+Alt+F9",TRUE,TRUE,TRUE},
	{VK_F10,"Shft+Ctl+Alt+F10",TRUE,TRUE,TRUE},
	{VK_F11,"Shft+Ctl+Alt+F11",TRUE,TRUE,TRUE},
	{VK_F12,"Shft+Ctl+Alt+F12",TRUE,TRUE,TRUE},
	{'0',"Shft+Ctl+Alt+0",TRUE,TRUE,TRUE},
	{'1',"Shft+Ctl+Alt+1",TRUE,TRUE,TRUE},
	{'2',"Shft+Ctl+Alt+2",TRUE,TRUE,TRUE},
	{'3',"Shft+Ctl+Alt+3",TRUE,TRUE,TRUE},
	{'4',"Shft+Ctl+Alt+4",TRUE,TRUE,TRUE},
	{'5',"Shft+Ctl+Alt+5",TRUE,TRUE,TRUE},
	{'6',"Shft+Ctl+Alt+6",TRUE,TRUE,TRUE},
	{'7',"Shft+Ctl+Alt+7",TRUE,TRUE,TRUE},
	{'8',"Shft+Ctl+Alt+8",TRUE,TRUE,TRUE},
	{'9',"Shft+Ctl+Alt+9",TRUE,TRUE,TRUE},
	{VK_END,"Shft+Ctl+Alt+End",TRUE,TRUE,TRUE},
	{VK_HOME,"Shft+Ctl+Alt+Home",TRUE,TRUE,TRUE},
	{VK_LEFT,"Shft+Ctl+Alt+←",TRUE,TRUE,TRUE},
	{VK_RIGHT,"Shft+Ctl+Alt+→",TRUE,TRUE,TRUE},
	{VK_UP,"Shft+Ctl+Alt+↑",TRUE,TRUE,TRUE},
	{VK_DOWN,"Shft+Ctl+Alt+↓",TRUE,TRUE,TRUE},
	{VK_PRIOR,"Shft+Ctl+Alt+PgUp",TRUE,TRUE,TRUE},
	{VK_NEXT,"Shft+Ctl+Alt+PgDn",TRUE,TRUE,TRUE},
	{VK_INSERT,"Shft+Ctl+Alt+Ins",TRUE,TRUE,TRUE},
	{VK_BACK,"Shft+Ctl+Alt+Back",TRUE,TRUE,TRUE},
	{VK_RETURN,"Shft+Ctl+Alt+Ret",TRUE,TRUE,TRUE},
	//終端
	{0,"",FALSE,FALSE,FALSE}
};

char* g_szFunc[] = 
{
	"File",
	"Edit",
	"Find",
	"Jump",
	"View",
	"Tool",
	"Settings",
	"Window",
	"Help",
	"others",
	""
};

#endif
