//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Editor.rc
//
#define IDB_EDIT_BROWSEURL              100
#define IDB_EDIT_CLIPVIEW               101
#define IDB_EDIT_DELTAB                 102
#define IDB_EDIT_DIRCOMPARE             103
#define IDB_EDIT_FILECOMPARE            104
#define IDB_EDIT_FILETOUCH              105
#define IDB_EDIT_INSASMCOMMENT          106
#define IDB_EDIT_INSCPPCOMMENT          107
#define IDB_EDIT_INSDAY                 108
#define IDB_EDIT_INSTAB                 109
#define IDB_EDIT_INSTIME                110
#define IDB_EDIT_INSVBCOMMENT           111
#define IDB_JUMP_DELMARK                112
#define IDB_JUMP_NEXTMARK               113
#define IDB_JUMP_PREVMARK               114
#define IDB_JUMP_SETMARK                115
#define IDB_LOGO                        116
#define IDB_MAILATTACH                  117
#define IDB_SECURITY_DECRIPT            118
#define IDB_SECURITY_ENCRIPT            119
#define IDB_SETREADONLY                 120
#define IDB_SOUNDICONS                  121
#define IDB_SPLASH                      122
#define IDB_UNSETREADONLY               123
#define IDB_VIEW_REDRAW                 124
#define IDB_WINDOW_ALLCLOSE             125
#define IDB_WINDOW_ARRANGE              126
#define IDB_WINDOW_CASCADE              127
#define IDB_WINDOW_CLOSE                128
#define IDB_WINDOW_NEW                  129
#define IDB_WINDOW_SPLIT                130
#define IDB_WINDOW_TILE_HORZ            131
#define IDB_WINDOW_TILE_VERT            132
#define IDB_WND_NEXT                    133
#define IDB_WND_PREV                    134
#define IDC_HAND                        135
#define IDD_ABOUTBOX                    200
#define IDD_CHECKEXECPASSWD             201
#define IDD_CLIPBOARDVIEW               202
#define IDD_CODECONV                    203
#define IDD_CONVSTATUS                  204
#define IDD_CUSTOM_FILEOPEN             205
#define IDD_DECRIPT                     206
#define IDD_DECRIPTSTATUS               207
#define IDD_DIALOG_JUMP                 208
#define IDD_DIRCOMPARE                  209
#define IDD_DIRCOMPARERESULT            210
#define IDD_DIRCOMPARESTATUS            211
#define IDD_ENCRIPT                     212
#define IDD_ENCRIPTSTATUS               213
#define IDD_EXECPASSWD                  214
#define IDD_FILECOMPARE                 215
#define IDD_FILECOMPARERESULT           216
#define IDD_FILECOPY                    217
#define IDD_FILEMOVE                    218
#define IDD_FILEPROPERTY                219
#define IDD_FILERENAME                  220
#define IDD_FILESEARCH                  221
#define IDD_FILESEARCHSTATUS            222
#define IDD_FILETOUCH                   223
#define IDD_FIND                        224
#define IDD_GREP                        225
#define IDD_GREPSTATUS                  226
#define IDD_KAIGYOCONV                  227
#define IDD_KAIGYOCONVSTATUS            228
#define IDD_KEYBINDLIST                 229
#define IDD_KEYOPE_DISP                 230
#define IDD_LICENSE                     231
#define IDD_MAILLIST                    232
#define IDD_MAILLISTSTATUS              233
#define IDD_MAILSEND                    234
#define IDD_MAILSENDSTATUS              235
#define IDD_MARKLINELIST                236
#define IDD_PROPPAGE1                   237
#define IDD_PROPPAGE10                  238
#define IDD_PROPPAGE11                  239
#define IDD_PROPPAGE12                  240
#define IDD_PROPPAGE2                   241
#define IDD_PROPPAGE3                   242
#define IDD_PROPPAGE4                   243
#define IDD_PROPPAGE5                   244
#define IDD_PROPPAGE6                   245
#define IDD_PROPPAGE7                   246
#define IDD_PROPPAGE8                   247
#define IDD_PROPPAGE9                   248
#define IDD_REPLACE                     249
#define IDD_WCNTSTATUS                  250
#define IDD_WORDCOUNT                   251
#define IDD_HTMLOPEN                    252
#define IDD_HTMLOPENSTATUS              253
#define IDD_HTMLOPENRESULT              254
#define CG_IDR_POPUP_EDITOR_VIEW        255
#define IDR_EDITORTYPE                  256
#define IDR_MAINFRAME                   257
#define IDR_TOOLBAR                     258
#define IDR_TOOLBAR_EDIT                259
#define IDR_TOOLBAR_FIND                260
#define IDR_TOOLBAR_JMP                 261
#define IDR_TOOLBAR_TOOLS               262
#define IDR_TOOLBAR_WND                 263
#define IDR_LAUGHICON                   264
#define IDSOUND_ABOUTDLG                265
#define IDS_FOPEN_ERR                   300
#define IDS_CANTACCESS_FILE             301
#define IDS_FILEACCESS_ERROR            302
#define IDS_INFOPEN_ERR                 303
#define IDS_OUTFOPEN_ERR                304
#define IDS_FILEKIND                    305
#define IDS_BROWSE                      306
#define IDS_INPUT_FOLDER                307
#define IDS_INPUT_FILEKIND              308
#define IDS_FOPEN_AS_READONLY           309
#define IDS_INPUT_FINDSTRING            310
#define IDS_FINDEND                     311
#define IDS_FINDENDMSG                  312
#define IDS_REPLACEEND                  313
#define IDS_REPLACEENDMSG               314
#define IDS_FINDFILE_NOTFOUND           315
#define IDS_GREPEND                     316
#define IDS_GREPCANCEL                  317
#define IDS_NOGREPFOLDER                318
#define IDS_GREPFILE_NOTFOUND           319
#define IDS_GERP_TITLE                  320
#define IDS_GREP_MATCHCOUNT             321
#define IDS_ASCIIDUMP_TITLE             322
#define IDS_SJISDUMP_TITLE              323
#define IDS_CONVEND                     324
#define IDS_CONVERR                     325
#define IDS_CONVCANCEL                  326
#define IDS_NOCONVFOLDER                327
#define IDS_CONVZERO                    328
#define IDS_CONVKIND_ERR                329
#define IDS_CANTGET_CONVTMPFNAME        330
#define IDS_CANTMAKE_CONVTMPFILE        331
#define IDS_CONV_TITLE                  332
#define IDS_CONV_TITLE2                 333
#define IDS_CONV_FILECOUNT              334
#define IDS_CONV_MEMO                   335
#define IDS_CONV_FOLDER_TITLE           336
#define IDS_CONV_LIST_TITLE             337
#define IDS_CONV_MSG_BINARY             338
#define IDS_CONV_MSG_ASCII              339
#define IDS_CONV_MSG_UNKNOWN            340
#define IDS_CONV_MSG_SJISEXIST          341
#define IDS_CONV_MSG_JISEXIST           342
#define IDS_CONV_MSG_EUCEXIST           343
#define IDS_CONV_SJIS2EUC               344
#define IDS_CONV_SJIS2JIS               345
#define IDS_CONV_EUC2SJIS               346
#define IDS_CONV_EUC2JIS                347
#define IDS_CONV_JIS2SJIS               348
#define IDS_CONV_JIS2EUC                349
#define IDS_CONV_OUT_RENAMEERR          350
#define IDS_CONV_IN_RENAMEERR           351
#define IDS_KAIGYOCONVEND               352
#define IDS_KAIGYOCONVCANCEL            353
#define IDS_NOKAIGYOCONVFOLDER          354
#define IDS_KAIGYOCONVZERO              355
#define IDS_KAIGYOCONVKIND_ERR          356
#define IDS_CANTGET_KAIGYOCONVTMPFNAME  357
#define IDS_CANTMAKE_KAIGYOCONVTMPFILE  358
#define IDS_KAIGYOCONV_TITLE            359
#define IDS_KAIGYOCONV_TITLE2           360
#define IDS_KAIGYOCONV_FILECOUNT        361
#define IDS_KAIGYOCONV_MEMO             362
#define IDS_KAIGYOCONV_FOLDER_TITLE     363
#define IDS_KAIGYOCONV_LIST_TITLE       364
#define IDS_KAIGYOCONV_MSG_BINARY       365
#define IDS_KAIGYOCONV_MSG_UNKNOWN      366
#define IDS_KAIGYOCONV_MSG_CRLFEXIST    367
#define IDS_KAIGYOCONV_MSG_LFEXIST      368
#define IDS_KAIGYOCONV_MSG_CREXIST      369
#define IDS_KAIGYOCONV_CRLF2LF          370
#define IDS_KAIGYOCONV_CRLF2CR          371
#define IDS_KAIGYOCONV_LF2CRLF          372
#define IDS_KAIGYOCONV_LF2CR            373
#define IDS_KAIGYOCONV_CR2CRLF          374
#define IDS_KAIGYOCONV_CR2LF            375
#define IDS_KAIGYOCONV_OUT_RENAMEERR    376
#define IDS_KAIGYOCONV_IN_RENAMEERR     377
#define IDS_NOWCOUNTFOLDER              378
#define IDS_WCOUNTEND                   379
#define IDS_WCOUNTCANCEL                380
#define IDS_WCOUNTZERO                  381
#define IDS_WCOUNT_TITLE                382
#define IDS_WCOUNT_FILECOUNT            383
#define IDS_WCOUNT_MEMO                 384
#define IDS_WCOUNT_MEMO2                385
#define IDS_WCOUNT_MEMO3                386
#define IDS_WCOUNT_MEMO4                387
#define IDS_WCOUNT_FOLDER_TITLE         388
#define IDS_WCOUNT_LIST_TITLE           389
#define IDS_NOFSEARCHFOLDER             390
#define IDS_FSEARCHEND                  391
#define IDS_FSEARCHCANCEL               392
#define IDS_FSEARCH_TITLE               393
#define IDS_FSEARCH_FILECOUNT           394
#define IDS_NOENCRIPTFOLDER             395
#define IDS_ENCRIPTEND                  396
#define IDS_ENCRIPTZERO                 397
#define IDS_ENCRIPTCANCEL               398
#define IDS_INPUT_ENCRIPTKEY            399
#define IDS_LESS16_ENCRIPTKEY           400
#define IDS_ODD_ENCRIPTKEY              401
#define IDS_ASCIONLY_ENCRIPTKEY         402
#define IDS_ASCIONLY_ENCRIPTKEY2        403
#define IDS_CANTGET_ENCRIPTTMPFNAME     404
#define IDS_CANTMAKE_ENCRIPTTMPFILE     405
#define IDS_ENCRYPTKEY                  406
#define IDS_ENCRYPT_TITLE               407
#define IDS_ENCRYPT_FILECOUNT           408
#define IDS_ENCRYPT_MEMO                409
#define IDS_ENCRYPT_FOLDER_TITLE        410
#define IDS_ENCRYPT_LIST_TITLE          411
#define IDS_ENCRYPT_RESULTMSG           412
#define IDS_ENCRYPT_PARAMERR            413
#define IDS_ENCRYPT_FACCESSERR          414
#define IDS_ENCRYPT_OUT_RENAMEERR       415
#define IDS_ENCRYPT_IN_RENAMEERR        416
#define IDS_NODECRIPTFOLDER             417
#define IDS_DECRIPTEND                  418
#define IDS_DECRIPTZERO                 419
#define IDS_DECRIPTCANCEL               420
#define IDS_INPUT_DECRIPTKEY            421
#define IDS_LESS16_DECRIPTKEY           422
#define IDS_ODD_DECRIPTKEY              423
#define IDS_ASCIONLY_DECRIPTKEY         424
#define IDS_ASCIONLY_DECRIPTKEY2        425
#define IDS_CANTGET_DECRIPTTMPFNAME     426
#define IDS_CANTMAKE_DECRIPTTMPFILE     427
#define IDS_DECRYPTKEY                  428
#define IDS_DECRYPT_TITLE               429
#define IDS_DECRYPT_FILECOUNT           430
#define IDS_DECRYPT_MEMO                431
#define IDS_DECRYPT_FOLDER_TITLE        432
#define IDS_DECRYPT_LIST_TITLE          433
#define IDS_DECRYPT_RESULTMSG           434
#define IDS_DECRYPT_PARAMERR            435
#define IDS_DECRYPT_FACCESSERR          436
#define IDS_DECRYPT_FCOLLUPT            437
#define IDS_DECRYPT_OUT_RENAMEERR       438
#define IDS_DECRYPT_IN_RENAMEERR        439
#define IDS_FILECOMPARE_SEL1FILE        440
#define IDS_FILECOMPARE_SEL2FILE        441
#define IDS_FILECOMPARE_READ1FILE       442
#define IDS_FILECOMPARE_READ2FILE       443
#define IDS_FILECOMPARE_COMPFILE        444
#define IDS_FILECOMPARE_OUTRESULT       445
#define IDS_NO1STDIR_CMP                446
#define IDS_NO2NDDIR_CMP                447
#define IDS_NOMORE_NEXTDIFF             448
#define IDS_NOMORE_PREVDIFF             449
#define IDS_1STZERO_FILECMP             450
#define IDS_2NDZERO_FILECMP             451
#define IDS_TIME                        452
#define IDS_FILECOMPARE_BINARY          453
#define IDS_FILECOMPARE_TITLE           454
#define IDS_FILECOMPARECANCEL           455
#define IDS_FILECOMPARENG               456
#define IDS_FILECOMPARE_END             457
#define IDS_FILECOMPARE_END2            458
#define IDS_INPUT1STDIR                 459
#define IDS_INPUT2NDDIR                 460
#define IDS_INPUTDIFFDIR                461
#define IDS_1STZERO_DIRCMP              462
#define IDS_2NDZERO_DIRCMP              463
#define IDS_DIRCOMPARE_MAKE1DIR         464
#define IDS_DIRCOMPARE_MAKE2DIR         465
#define IDS_DIRCOMPARE_NOWCOMPARE       466
#define IDS_DIRCOMPARE_OUTRESULT        467
#define IDS_DIRCOMPARE_RESULTMSG1       468
#define IDS_DIRCOMPARE_RESULTMSG2       469
#define IDS_DIRCOMPARE_RESULTMSG3       470
#define IDS_DIRCOMPARE_TITLE            471
#define IDS_DIRCOMPARE_LIST_TITLE       472
#define IDS_DIRCOMPARE_1STDIR           473
#define IDS_DIRCOMPARE_2NDDIR           474
#define IDS_DIRCOMPARE_TITLE2           475
#define IDS_DIRCOMPARECANCEL            476
#define IDS_DIRCOMPARENG                477
#define IDS_DIRCOMAPRE_END              478
#define IDS_PRINTLAYOUTHELP             479
#define IDS_LOGOBMPLOAD_NG              480
#define IDS_SPLASHTIME_ERR              481
#define IDS_AUTOSAVETIME_ERR            482
#define IDS_LOGOX_ERR                   483
#define IDS_LOGOY_ERR                   484
#define IDS_SET_PASSWD                  485
#define IDS_INPUT_PASSWD                486
#define IDS_INPUT_ORGANIZATION          487
#define IDS_INPUT_USERNAME              488
#define IDS_NOFILE_INTHISDIR            489
#define IDS_CONFIRM_REREAD1             490
#define IDS_CONFIRM_REREAD2             491
#define IDS_NOTALLDISP_CLIP             492
#define IDS_ERRCHANGEFILEATTR           493
#define IDS_HTMLHELP_OPEN_ERR           494
#define IDS_BROUSERKICK_ERR             495
#define IDS_NOTABOVEURL                 496
#define IDS_MAILERKICK_ERR              497
#define IDS_NOTABOVEEMAIL               498
#define IDS_SOFTKICK_ERR                499
#define IDS_LICENSE_OK                  500
#define IDS_LICENSE_NG                  501
#define IDS_INITIALNOTE                 502
#define IDS_EXPIRED                     503
#define IDS_TOOL_OPE_STARTENDRECORD     504
#define IDS_TOOL_OPE_ENDRECORD          505
#define IDS_TOOL_OPE_STARTRECORD        506
#define IDS_KEYOPE_PARSEERR             507
#define IDS_KEYOPE_STARTRECORD          508
#define IDS_KEYOPE_STEPDOEND            509
#define IDS_KEYOPE_STEPDOEND2           510
#define IDS_KEYOPE_FOPENERR             511
#define IDS_NOT_KEYOPEFILE              512
#define IDS_KEYOPE_OPENEND              513
#define IDS_KEYOPE_UNSAVED              514
#define IDS_KEYOPE_RECORDEND            515
#define IDS_NOMARKLINE_NEXT             517
#define IDS_NOTSEL_MARKLINE             518
#define IDS_OUTOFJUMPRANGE              519
#define IDS_PAREN_NOTFOUND              520
#define IDS_UUENCODE_INFILE_TITLE       521
#define IDS_UUENCODE_RESULT_TITLE       522
#define IDS_NO_UUDECODEHEADER           523
#define IDS_END_UUDECODE                524
#define IDS_NO_UUDECODEFOOTER           525
#define IDS_ILLEGAL_LINE_UUDECODE       526
#define IDS_UUDECODE_OUTFILE_TITLE      527
#define IDS_NG_ENCODE                   528
#define IDS_BASE64_INFILE_TITLE         529
#define IDS_BASE64_RESULT_TITLE         530
#define IDS_END_BASE64DECODE            531
#define IDS_ILLEGAL_LINE_BASE64DECODE   532
#define IDS_BASE64_OUTFILE_TITLE        533
#define IDS_QUOTED_INFILE_TITLE         534
#define IDS_QUOTED_RESULT_TITLE         535
#define IDS_END_QUOTEDDECODE            536
#define IDS_ILLEGAL_LINE_QUOTEDDECODE   537
#define IDS_QUOTE_OUTFILE_TITLE         538
#define IDS_PASSWORD_NG                 539
#define IDS_SHELLDLL_NOTFOUND           540
#define IDS_CANTACCESS_FOLDER           541
#define IDS_CANTACCESS_FOLDERMV         542
#define IDS_INPUT_EXISTFOLDER           543
#define IDS_INPUT_AFTERNAME             544
#define IDS_INPUT_DIFFNAME              545
#define IDS_INVALIDCHAR_AFTERNAME       546
#define IDS_FTOUCHEND                   547
#define IDS_FTOUCHCANCEL                548
#define IDS_FILETOUCH_INVALIDDATE       549
#define IDS_SMTP_CONNECTERR             550
#define IDS_SMTP_LOCALHOSTNAMEERR       551
#define IDS_SMTP_LOCALIPERR             552
#define IDS_SMTP_SENDERR                553
#define IDS_SMTP_NOMAILSERVICE          554
#define IDS_SMTP_SENDEND                555
#define IDS_SMTP_NOFROM                 556
#define IDS_SMTP_NOSERVER               557
#define IDS_SMTP_NOTO                   558
#define IDS_SMTP_COMMASEPARATE          559
#define IDS_SMTP_DLLNOTFOUND            560
#define IDS_SMTP_ATTACHFILEOPENERR      561
#define IDS_SMTP_RESCODE_211            562
#define IDS_SMTP_RESCODE_214            563
#define IDS_SMTP_RESCODE_220            564
#define IDS_SMTP_RESCODE_221            565
#define IDS_SMTP_RESCODE_250            566
#define IDS_SMTP_RESCODE_251            567
#define IDS_SMTP_RESCODE_252            568
#define IDS_SMTP_RESCODE_354            569
#define IDS_SMTP_RESCODE_421            570
#define IDS_SMTP_RESCODE_450            571
#define IDS_SMTP_RESCODE_451            572
#define IDS_SMTP_RESCODE_500            573
#define IDS_SMTP_RESCODE_501            574
#define IDS_SMTP_RESCODE_502            575
#define IDS_SMTP_RESCODE_503            576
#define IDS_SMTP_RESCODE_504            577
#define IDS_SMTP_RESCODE_550            578
#define IDS_SMTP_RESCODE_551            579
#define IDS_SMTP_RESCODE_552            580
#define IDS_SMTP_RESCODE_553            581
#define IDS_SMTP_RESCODE_554            582
#define IDS_RAS_NOUSERNAME              583
#define IDS_RAS_NOPASSWD                584
#define IDS_RAS_CONNECTERR              585
#define IDS_RASCONNECT                  586
#define IDS_RASDISCONNECT               587
#define IDS_RASCONNECTERR               588
#define IDS_RASCONNECTEND               589
#define IDS_RASISCONNECT                590
#define IDS_POP_NOSERVER                591
#define IDS_POP_NOUSER                  592
#define IDS_POP_NOPASSWD                593
#define IDS_POP_LISTZERO                594
#define IDS_POP_DLLNOTFOUND             595
#define IDS_POP_CONNECTERR              596
#define IDS_POP_SENDERR                 597
#define IDS_POP_TOPERR                  598
#define IDS_POP_LISTERR                 599
#define IDS_POP_RETRERR                 600
#define IDS_POP_DELERR                  601
#define IDS_POP_SELECTLIST              602
#define IDS_POP_TIMEOUT                 603
#define IDS_POP_DISCONNECTED            604
#define IDS_KEYBIND_RESET               605
#define IDS_KEYBIND_WRITEEND            606
#define IDS_KEYBIND_READEND             607
#define IDS_NOT_KEYBINDFILE             608
#define IDS_KEYBIND_INFILE_TITLE        609
#define IDS_KEYBIND_OUTFILE_TITLE       610
#define IDS_KEYBIND_ASSIGN              611
#define IDS_KEYBIND_NOTASSIGNED         612
#define IDS_KEYBIND_DEASSIGN            613
#define IDS_START_INCRIMENTALSEARCH     614
#define IDS_END_INCRIMENTALSEARCH       615
#define IDS_INCREMENTALSEARCH_NOW       616
#define IDS_INCREMENTALSEARCH           617
#define IDS_INCREMENTALSEARCH_E         618
#define IDS_INCREMENTALSEARCH_S         619
#define IDS_INCREMENTALSEARCH_END       620
#define IDS_FILTER_ALLFILE              621
#define IDS_FILTER_BATFILE              622
#define IDS_FILTER_INIFILE              623
#define IDS_FILTER_MAKFILE              624
#define IDS_FONTNAME_ABOUTDLG           625
#define IDS_FONTNAME_DISP               626
#define IDS_FONTNAME_DISP2              627
#define IDS_FONTNAME_PRINT              628
#define IDS_FONTNAME_PRINT2             629
#define IDS_SHORTCUTNAME_TOXERXES       630
#define IDS_FILEEXCEPTION_NONE          631
#define IDS_FILEEXCEPTION_GENGERIC      632
#define IDS_FILEEXCEPTION_NOTFOUND      633
#define IDS_FILEEXCEPTION_BADPATH       634
#define IDS_FILEEXCEPTION_TOOMANY       635
#define IDS_FILEEXCEPTION_ACCESSDENY    636
#define IDS_FILEEXCEPTION_INVALIDFILE   637
#define IDS_FILEEXCEPTION_REMOVECURRDIR 638
#define IDS_FILEEXCEPTION_DIRFULL       639
#define IDS_FILEEXCEPTION_BADSEEK       640
#define IDS_FILEEXCEPTION_HARDIO        641
#define IDS_FILEEXCEPTION_SHAREVIOLATION 642
#define IDS_FILEEXCEPTION_LOCKVIOLATION 643
#define IDS_FILEEXCEPTION_DISKFULL      644
#define IDS_FILEEXCEPTION_ENDOFFILE     645
#define IDS_MAILLIST_GET                646
#define IDS_MAILRECVERR                 647
#define IDS_MAILRECVEND                 648
#define IDS_MAILCOUNT                   649
#define IDS_MAILSERVER_CONNECT          650
#define IDS_MAIL_SEND                   651
#define IDS_MAIL_SENDEND                652
#define IDS_SELECTATTACHFILE            653
#define IDS_LINENO_FORMAT               654
#define IDS_DAYSTYLE_NONE               655
#define IDS_DAYSTYLE_YYYY_MM_DD         656
#define IDS_DAYSTYLE_YYYY_MM_DD2        657
#define IDS_DAYSTYLE_YY_MM_DD           658
#define IDS_DAYSTYLE_YY_MM_DD2          659
#define IDS_DAYSTYLE_MM_DD              660
#define IDS_DAYSTYLE_MM_DD2             661
#define IDS_HOURSTYLE_NONE              662
#define IDS_HOURSTYLE_HH_MM             663
#define IDS_HOURSTYLE_HH_MM2            664
#define IDS_HOURSTYLE_AMPM_HH_MM        665
#define IDS_HOURSTYLE_AMPM_HH_MM2       666
#define IDS_LINESTYLE_LINE_OFFS_ALL     667
#define IDS_LINESTYLE_LINE_OFFS_ALL2    668
#define IDS_LINESTYLE_LINE_OFFS         669
#define IDS_LINESTYLE_LINE_OFFS2        670
#define IDS_LINESTYLE_LINE_ALL          671
#define IDS_LINESTYLE_LINE_ALL2         672
#define IDS_LINESTYLE_ALL               673
#define IDS_LINESTYLE_ALL2              674
#define IDS_LINESTYLE_LINE              675
#define IDS_LINESTYLE_LINE2             676
#define IDS_LINESTYLE_OFFS              677
#define IDS_LINESTYLE_OFFS2             678
#define IDS_INSMODE_INSERT              679
#define IDS_INSMODE_OVERWRITE           680
#define IDS_READONLYMODE_READONLY       681
#define IDS_READONLYMODE_WRITEOK        682
#define IDS_INDICATOR_GYORETU           683
#define IDS_INDICATOR_BYTE              684
#define IDS_INDICATOR_INS               685
#define IDS_INDICATOR_READONLY          686
#define IDS_INDICATOR_TIME              687
#define IDS_INDICATOR_CHARCODE          688
#define IDS_INDICATOR_KANA              689
#define IDS_INDICATOR_CAPS              690
#define IDS_INDICATOR_NUM               691
#define IDS_INDICATOR_SCRL              692
#define IDS_FILEPROP_MTIME              693
#define IDS_FILEPROP_INFO               694
#define IDS_FILEPROP_BINARY             695
#define IDS_FILEPROP_EUC                696
#define IDS_FILEPROP_JIS                697
#define IDS_FILEPROP_UNKNOWN            698
#define IDS_FILEPROP_PATH               699
#define IDS_SOUND_XERXES_STARTEND       700
#define IDS_SOUND_XERXES_START          701
#define IDS_SOUND_XERXES_END            702
#define IDS_SOUND_MESSAGE               703
#define IDS_SOUND_MESSAGE_INFO          704
#define IDS_SOUND_MESSAGE_STOP          705
#define IDS_SOUND_MESSAGE_QUESTION      706
#define IDS_SOUND_MESSAGE_EXCLAIM       707
#define IDS_SOUND_WINDOW                708
#define IDS_SOUND_WINDOW_MINIMIZE       709
#define IDS_SOUND_WINDOW_MAXIMIZE       710
#define IDS_SOUND_WINDOW_RESTORE        711
#define IDS_SOUND_WINDOW_NEXT           712
#define IDS_SOUND_WINDOW_PREV           713
#define IDS_SOUND_WINDOW_CLOSE          714
#define IDS_SOUND_WINDOW_ALLCLOSE       715
#define IDS_SOUND_FILE                  716
#define IDS_SOUND_FILE_NEW              717
#define IDS_SOUND_NONE                  718
#define IDS_FONTNAME_DISP3              719
#define IDS_FONTNAME_PRINT3             720
#define IDS_FONTNAME_DISP4              721
#define IDS_FONTNAME_PRINT4             722
#define IDS_DIRCOMPARE_RESULTMSG4       723
#define IDS_WCOUNT_LIST_SUM             724
#define IDS_NOMARKLINE_PREV             725
#define IDS_APOP_CONNECTERR             726
#define IDS_PROPSHT_CAPTION             727
#define IDS_PROPSHT_CAPTION1            728
#define CG_IDS_PHYSICAL_MEM             729
#define CG_IDS_DISK_SPACE               730
#define CG_IDS_DISK_SPACE_UNAVAIL       731
#define IDS_MAILACCOUNT_0               732
#define IDS_MAILACCOUNT_1               733
#define IDS_MAILACCOUNT_2               734
#define IDS_MAILACCOUNT_3               735
#define IDS_MAILACCOUNT_4               736
#define IDS_MAILACCOUNT_5               737
#define IDS_MAILACCOUNT_6               738
#define IDS_MAILACCOUNT_7               739
#define IDS_REGEX_COMPERR               740
#define IDS_INPUT_REQUESTPATH           741
#define IDS_INPUT_PROXYIPADDRESS        742
#define IDS_HTTP_INVALIDFORMAT          743
#define IDS_HTTP_ASCIONLY               744
#define IDS_HTTP_DLLNOTFOUND            745
#define IDS_HTTP_CONNECTERR             746
#define IDS_HTTP_SENDERR                747
#define IDS_HTTP_TIMEOUT                748
#define IDS_HTTP_DISCONNECTED           749
#define IDS_HTTP_TITLE                  750
#define IDS_HTTP_CONNECT                751
#define IDS_HTTP_GET                    752
#define IDS_HTTPOPEN_END                753
#define IDS_HTTPOPEN_CANCEL             754
#define IDS_HTTP_FILEOPENERR            755
#define IDS_INPUT_USERID                756
#define IDS_INPUT_PASSWORD              757
#define IDR_AUTH                        758
#define IDD_BASICAUTH                   759
#define IDC_RADIO_4TAB                  1000
#define IDC_RADIO_8TAB                  1001
#define IDC_BUTTON_STSBARFONT           1002
#define IDC_BUTTON_TXTCLR               1003
#define IDC_RADIO_CARET_IBEAM           1004
#define IDC_RADIO_2TAB                  1005
#define IDC_BUTTON_INVTXTCLR            1006
#define IDC_RADIO_CARET_SQUARE          1007
#define IDC_BUTTON_BKCLR                1008
#define IDC_RADIO_CARETMOVE             1009
#define IDC_BUTTON_INVBKCLR             1010
#define IDC_RADIO_CARETSTAY             1011
#define IDC_BUTTON_COMMENTCLR           1012
#define IDC_RADIO_WORDTYPE              1013
#define IDC_CHECK_DISPLINENO            1014
#define IDC_RADIO_NOTEPADTYPE           1015
#define IDC_BUTTON_KEYWORD1CLR          1016
#define IDC_RADIO_ACCEL_1               1017
#define IDC_BUTTON_KEYWORD2CLR          1018
#define IDC_LINENO                      1019
#define IDC_RADIO_ACCEL_2               1020
#define IDC_EDIT_LINENO                 1021
#define IDC_BUTTON_LINENO               1022
#define IDC_RADIO_ACCEL_3               1023
#define IDC_CHECK_SAVEWINDOWPLACE       1024
#define IDC_CHECK_DISPCRLF              1025
#define IDC_RADIO_ACCEL_4               1026
#define IDC_CHECK_OPENNEWFILE           1027
#define IDC_BUTTON_CRLFCLR              1028
#define IDC_RADIO_ACCEL_5               1029
#define IDC_CHECK_MAXCLDWND             1030
#define IDC_BUTTON_KEYWORD4CLR          1031
#define IDC_RADIO_PASTETOP              1032
#define IDC_CHECK_CHDIRTOOPENFILE       1033
#define IDC_BUTTON_KEYWORD3CLR          1034
#define IDC_RADIO_PASTEEND              1035
#define IDC_EDIT_MAXMRU                 1036
#define IDC_CHECK_DISPRULER             1037
#define IDC_CHECK_FULLTITLE             1038
#define IDC_BUTTON_RULER                1039
#define IDC_CHECK_DISPEOFMARK           1040
#define IDC_CHECK_DISPTAB               1041
#define IDC_CHECK_NODOUBLEEXECUTE       1042
#define IDC_EDIT_FILEKIND               1043
#define IDC_BUTTON_TABCLR               1044
#define IDC_EDIT_FOLDER                 1045
#define IDC_CHECK_DISPSPACE             1046
#define IDC_CHECK_SHOWSPLASH            1047
#define IDC_CHECK_SUBFOLDER             1048
#define IDC_BUTTON_SPACECLR             1049
#define IDC_EDIT_SPLASHTIME             1050
#define IDC_CHECK_MATCHCASE             1051
#define IDC_CHECK_OUTOTHERFILE          1052
#define IDC_CHECK_DISPUNDERLINE         1053
#define IDC_CHECK_EXECPASSWD            1054
#define IDC_EDIT_DATE                   1055
#define IDC_CHECK_MATCHWHOLEWORD        1056
#define IDC_FOLDER                      1057
#define IDC_BUTTON_UNDERLINE            1058
#define IDC_EDIT_KEY                    1059
#define IDC_CHECK_ENABLESHELLOPEN       1060
#define IDC_EDIT_TIME                   1061
#define IDC_FILE                        1062
#define IDC_BUTTON_COMMENTCLR2          1063
#define IDC_CHECK_MAKESHORTCUTDSKTOP    1064
#define IDC_FILEKIND                    1065
#define IDC_COMBO_GREPSTR               1066
#define IDC_BUTTON_LINENOBACK           1067
#define IDC_CHECK_IMMAUTOOPEN           1068
#define IDC_GREPSTR                     1069
#define IDC_HYPERLINK                   1070
#define IDC_BUTTON_RULERBACK            1071
#define IDC_MATCHCOUNT                  1072
#define IDC_COMBO_CONVKIND              1073
#define IDC_BUTTON_MDIBKGND             1074
#define IDC_COMBO_INCODE                1074
#define IDC_BUTTON_COMMENTCLR3          1075
#define IDC_CONVKIND                    1076
#define IDC_CHECK_ASMCOMMENT            1077
#define IDC_FILECOUNT                   1078
#define IDC_CHECK_VBCOMMENT             1079
#define IDC_RADIO_CRLF                  1080
#define IDC_CHECK_CPPCOMMENT            1081
#define IDC_RADIO_LF                    1082
#define IDC_BUTTON_MARKLINE             1083
#define IDC_RADIO_CR                    1084
#define IDC_BUTTON_DIFFDELLINECLR       1085
#define IDC_CHECK_LINENO                1086
#define IDC_BUTTON_DIFFADDLINECLR       1087
#define IDC_EDIT_HEADERFORMAT           1088
#define IDC_BUTTON_DIRCMPDIFFFILECLR    1089
#define IDC_RADIO_HEADER_LEFT           1090
#define IDC_BUTTON_URLCLR               1091
#define IDC_RADIO_HEADER_CENTER         1092
#define IDC_BUTTON_EMAILCLR             1093
#define IDC_RADIO_HEADER_RIGHT          1094
#define IDC_CHECK_DISPURL               1095
#define IDC_EDIT_FOOTERFORMAT           1096
#define IDC_CHECK_DISPEMAIL             1097
#define IDC_BUTTON_LAYOUTHELP           1098
#define IDC_CHECK_QUOTE                 1099
#define IDC_RADIO_FOOTER_LEFT           1100
#define IDC_FILENAME                    1101
#define IDC_BUTTON_COMMENTCLR4          1102
#define IDC_RADIO_FOOTER_CENTER         1103
#define IDC_TITLE                       1104
#define IDC_CHECK_AUTOSAVE              1105
#define IDC_RADIO_FOOTER_RIGHT          1106
#define IDC_CTIME                       1107
#define IDC_EDIT_SAVEINTERVAL           1108
#define IDC_MTIME                       1109
#define IDC_CHECK_DELENDSPACES          1110
#define IDC_ATIME                       1111
#define IDC_EDIT_BLINKTIME              1112
#define IDC_CHECK_2DANGUMI              1113
#define IDC_CHECK_SPACE2TAB             1114
#define IDC_LOGSIZE                     1115
#define IDC_EDIT_KAISYA                 1116
#define IDC_ATTR                        1117
#define IDC_EDIT_USER                   1118
#define IDC_KAIGYO                      1119
#define IDC_CODE                        1120
#define IDC_EDIT_LICENSEKEY             1121
#define IDC_KAISYA                      1122
#define IDC_LINECNT                     1123
#define IDC_USER                        1124
#define IDC_EDIT_LOGOPOSX               1125
#define IDC_TABSIZE                     1126
#define IDC_EDIT_LOGOPOSY               1127
#define IDC_CHECK_LOGODISP              1128
#define IDC_EDIT_CLIP_CONTENTS          1129
#define IDC_KEYOPE_LIST                 1130
#define IDC_EDIT_OPERATIONNAME          1131
#define IDC_KEYOPE_FNAME                1132
#define IDC_LIST_CURRENTITEM            1133
#define IDC_LIST_ADDITEM                1134
#define IDC_BUTTON_ADD                  1135
#define IDC_BUTTON_DEL                  1136
#define IDC_COMBO_DAYSTYLE              1137
#define IDC_COMBO_HOURSTYLE             1138
#define IDC_COMBO_LINESTYLE             1139
#define IDC_LIST_MARKLINE               1140
#define IDC_RADIO_PRINTORIENTATION_TATE 1141
#define IDC_RADIO_PRINTORIENTATION_YOKO 1142
#define IDC_EDIT_YOHAKU_HIDARI          1143
#define IDC_EDIT_YOHAKU_UE              1144
#define IDC_EDIT_YOHAKU_MIGI            1145
#define IDC_MYHELP                      1146
#define IDC_EDIT_YOHAKU_SITA            1147
#define IDC_SETPASSWDBTN                1148
#define IDC_EDIT_EXECPASSWD             1149
#define IDC_FILE1_NAME                  1150
#define IDC_FILE2_NAME                  1151
#define IDC_COMPARE_STATUS              1152
#define IDC_STATUS                      1153
#define IDC_DELLINE_CNT                 1154
#define IDC_FILE1                       1155
#define IDC_ADDLINE_CNT                 1156
#define IDC_FILE2                       1157
#define IDC_TIME                        1158
#define IDC_BROWSE2                     1159
#define IDC_BROWSE1                     1160
#define IDC_DIR1                        1161
#define IDC_DIR2                        1162
#define IDC_DIR1_NAME                   1163
#define IDC_DIR2_NAME                   1164
#define IDC_DELFILE_CNT                 1165
#define IDC_ADDFILE_CNT                 1166
#define IDC_DIFFILE_CNT                 1167
#define IDC_REFRESHBTN                  1168
#define IDC_COMPAREFILE_CNT             1169
#define IDC_CHECK_RENAMEONCOLLISION     1170
#define IDC_FROMFILE                    1171
#define IDC_EDIT_TOFILE                 1172
#define IDC_RADIO_XERXES                1173
#define IDC_RADIO_FAVARITE              1174
#define IDC_EDIT_BMPFILEPATH            1175
#define IDC_REF                         1176
#define IDC_RADIO_POSSITEI              1177
#define IDC_RADIO_TILE                  1178
#define IDC_FIND                        1179
#define IDC_COMBO_FINDSTRING            1180
#define IDC_CHECK_WHOLEWORD             1181
#define IDC_RADIO_UP                    1182
#define IDC_RADIO_DOWN                  1183
#define IDC_EDIT_MAILADDRESS            1184
#define IDC_COMBO_REPLACESTRING         1185
#define IDC_EDIT_SMTPSERVER             1186
#define IDC_EDIT_POPSERVER              1187
#define IDC_EDIT_POPUSERNAME            1188
#define IDC_EDIT_POPPASSWD              1189
#define IDC_RADIO_ENCODE_BASE64         1190
#define IDC_RADIO_ENCODE_QUOTED         1191
#define IDC_EDIT_SIGNATURE              1192
#define IDC_RADIO_ENCODE_UUENCODE       1193
#define IDC_COMBO_DIALUPENTRY           1194
#define IDC_COMBO_ACCOUNT               1195
#define IDC_EDIT_SUBJECT                1196
#define IDC_EDIT_CC                     1197
#define IDC_LIST_ATTACHFILE             1198
#define IDC_CHECK_AUTODISCONNECT        1199
#define IDC_EDIT_BCC                    1200
#define IDC_CHECK_DIALUP                1201
#define IDC_EDIT_REPLYTO                1202
#define IDC_EDIT_RASUSERNAME            1203
#define IDC_EDIT_REFERENCE              1204
#define IDC_EDIT_RASPASSWD              1205
#define IDC_COMBO_TO                    1206
#define IDC_CHECK_SUBJECTAUTOSET        1207
#define IDC_CHECK_SENDMSGID             1208
#define IDC_LIST_MAIL                   1209
#define IDC_CHECK_SENDDATE              1210
#define IDC_MAILCOUNT                   1211
#define IDC_POPSERVER                   1212
#define IDC_POPUSER                     1213
#define IDC_COMBO_FILEEXT               1214
#define IDC_COMBO_DISPFONTNAME          1215
#define IDC_COMBO_PRINTFONTNAME         1216
#define IDC_LIST_KEY                    1217
#define IDC_COMBO_DISPFONTSIZE          1218
#define IDC_CHECK_CTRL                  1219
#define IDC_COMBO_PRINTFONTSIZE         1220
#define IDC_CHECK_SHIFT                 1221
#define IDC_COMBO_FUNC                  1222
#define IDC_LIST_CMD                    1223
#define IDC_SETUMEI                     1224
#define IDC_CHECK_ALT                   1225
#define IDC_BUTTON_ASSIGN               1226
#define IDC_BUTTON_KAIJYO               1227
#define IDC_LIST_KEYBIND                1228
#define IDC_BUTTON_LIST                 1229
#define IDC_BUTTON_RESET                1230
#define IDC_BUTTON_WRITE                1231
#define IDC_BUTTON_READ                 1232
#define IDC_BUTTON_HELP                 1233
#define IDC_CMDID                       1234
#define IDC_PATH                        1235
#define IDC_EDIT_PREVIEW                1236
#define IDC_SOFTNAME                    1237
#define IDC_CREDIT                      1238
#define IDC_COMBO_FOLDER1               1239
#define IDC_COMBO_FOLDER2               1240
#define IDC_TREE_SOUNDS                 1241
#define IDC_COMBO_WAVEFILES             1242
#define IDC_BUTTON_TEST                 1243
#define IDC_CHECK_DISPOSITION           1244
#define IDC_RADIO_AUTH_STANDARD         1245
#define IDC_RADIO_AUTH_APOP             1246
#define IDC_BROWSE                      1247
#define IDC_JUMPBTN                     1248
#define IDC_FILEATTACH                  1249
#define IDC_REPLACENEXT                 1250
#define IDC_RECVBTN                     1251
#define IDC_REPLACEALL                  1252
#define IDC_FILEDETACH                  1253
#define IDC_DELBTN                      1254
#define IDC_LISTACCOUNT                 1255
#define IDC_LISTSERVER                  1256
#define IDC_MSENDSERVER                 1257
#define IDC_MSENDACCOUNT                1258
#define IDC_APPICON                     1259
#define IDC_CHECK_REGEX                 1260
#define IDC_COMBO_REQUESTPATH           1261
#define IDC_CHECK_USEPROXY              1262
#define IDC_EDIT_PROXYIPADDRESS         1263
#define IDC_EDIT_HEADER                 1264
#define IDC_PROGRESS_BYTE               1265
#define IDC_BYTE                        1266
#define IDC_AUTH_SITE                   1267
#define IDC_AUTH_REALM                  1268
#define IDC_EDIT_AUTH_USER              1269
#define IDC_EDIT_AUTH_PASSWD            1270
#define IDC_CHECK_SAVETHISPASSWD        1271
#define IDS_INCODEKIND_ERR				1272
#define IDS_CODECONV_TO_EUC				1273
#define IDS_CODECONV_TO_SJIS			1274
#define IDS_CODECONV_TO_JIS				1275
#define	IDS_INCODE_AUTO					1276
#define	IDS_INCODE_EUC					1277
#define IDS_INCODE_SJIS					1278
#define	IDS_INCODE_JIS					1279
#define ID_EDIT_FINDREVCONTINUE         32748
#define ID_VIEW_LINENO                  32771
#define ID_VIEW_TAB4                    32772
#define ID_VIEW_TAB8                    32773
#define ID_SETTINGS                     32776
#define ID_EDIT_SELECTALL               32779
#define ID_EDIT_DEL                     32781
#define ID_EDIT_JUMP2TOP                32782
#define ID_EDIT_JUMP2BOTTOM             32783
#define ID_EDIT_JUMP2LINE               32784
#define ID_EDIT_FINDCONTINUE            32787
#define ID_WINDOW_ALLCLOSE              32789
#define ID_FILE_ALLSAVE                 32790
#define ID_VIEW_CRLF                    32791
#define ID_VIEW_RULER                   32792
#define ID_FILE_OPENONEXIT              32797
#define ID_WINDOW_CLOSE                 32798
#define ID_EDIT_GREP                    32801
#define ID_PARENTHESIS                  32805
#define ID_VIEW_TAB                     32806
#define ID_VIEW_ZENKAKUSPACE            32807
#define ID_EDIT_TAB2SPACE               32808
#define ID_EDIT_SPACE2TAB               32809
#define ID_EDIT_SPACE_ZEN2HAN           32810
#define ID_EDIT_SPACE_HAN2ZEN           32811
#define ID_EDIT_CODECONV                32813
#define ID_EDIT_ASCIIDUMP               32815
#define ID_EDIT_SJISDUMP                32816
#define ID_FILE_REREAD                  32817
#define ID_FILE_PROPERTY                32819
#define ID_EDIT_SETREADONLY             32820
#define ID_EDIT_UNSETREADONLY           32821
#define ID_EDIT_KATAKANA_HAN2ZEN        32822
#define ID_EDIT_KATAKANA_ZEN2HAN        32823
#define ID_EDIT_WORDCOUNT               32824
#define ID_VIEW_UNDERLINE               32825
#define ID_VIEW_CARET_IBEAM             32826
#define ID_VIEW_CARET_SQUARE            32827
#define ID_VIEW_TAB_4                   32828
#define ID_VIEW_TAB_8                   32829
#define ID_EDIT_FILESEARCH              32830
#define ID_EDIT_ALNUM_HAN2ZEN           32831
#define ID_EDIT_ALNUM_ZEN2HAN           32832
#define ID_HELP_LICENSE                 32833
#define ID_EDIT_DELTOPSPACES            32834
#define ID_HELP_CONTENT                 32835
#define ID_EDIT_INSTAB                  32836
#define ID_EDIT_DELTAB                  32837
#define ID_ALLSAVE_EXIT                 32848
#define ID_FILE_SAVECLOSE               32849
#define ID_EDIT_CLIPVIEW                32850
#define ID_EDIT_TAGJUMP                 32851
#define ID_TOOL_OPE_STARTENDRECORD      32852
#define ID_TOOL_OPE_SAVE                32853
#define ID_TOOL_OPE_DO                  32854
#define ID_TOOL_OPE_OPEN                32855
#define ID_TOOL_OPE_DISP                32856
#define ID_TOOL_OPE_STEPDO              32858
#define ID_TOOL_OPE_STEPDO_NEXT         32859
#define ID_TOOL_OPE_STEPDO_END          32860
#define ID_WND_NEXT                     32861
#define ID_WND_PREV                     32862
#define ID_EDIT_CLEARUNDOBUF            32863
#define ID_EDIT_INSCPPCOMMENT           32864
#define ID_EDIT_INSVBCOMMENT            32865
#define ID_EDIT_INSASMCOMMENT           32866
#define ID_VIEW_REDRAW                  32867
#define ID_VIEW_EOF                     32869
#define ID_JUMP_SETMARK                 32870
#define ID_JUMP_DELMARK                 32871
#define ID_JUMP_NEXTMARK                32872
#define ID_JUMP_PREVMARK                32873
#define ID_JUMP_MARKLIST                32874
#define ID_JUMP_ALLDELMARK              32875
#define ID_EDIT_INSDAY                  32876
#define ID_EDIT_INSTIME                 32877
#define ID_EDIT_INCRIMENTALSEARCH       32878
#define ID_EDIT_AL2UPPER                32879
#define ID_EDIT_AL2LOWER                32880
#define ID_WORDSKIP2RIGHT               32881
#define ID_WORDSKIP2LEFT                32882
#define ID_WORDSELECT2RIGHT             32883
#define ID_WORDSELECT2LEFT              32884
#define ID_EDIT_UUDECODE                32885
#define ID_EDIT_BASE64DECODE            32886
#define ID_EDIT_QUOTEDDECODE            32887
#define ID_SECURITY_ENCRIPT             32889
#define ID_SECURITY_DECRIPT             32890
#define ID_EDIT_UUENCODE                32891
#define ID_EDIT_BASE64ENCODE            32892
#define ID_EDIT_QUOTEDENCODE            32893
#define ID_EDIT_FILECOMPARE             32894
#define ID_EDIT_NEXTDIFF                32895
#define ID_EDIT_PREVDIFF                32896
#define ID_FILE_OPENSAMENAME            32897
#define ID_EDIT_JUMP2TOPSELECT          32898
#define ID_EDIT_JUMP2BOTTOMSELECT       32899
#define ID_EDIT_DIRCOMPARE              32900
#define ID_EDIT_DIRCMP_SYOSAI           32901
#define ID_FILE_COPY                    32902
#define ID_FILE_RENAME                  32903
#define ID_FILE_DELETE                  32904
#define ID_FILE_MOVE                    32905
#define ID_PARENTHESIS2                 32907
#define ID_PARENTHESIS_SELECT           32908
#define ID_EDIT_FILETOUCH               32909
#define ID_EDIT_BROWSEURL               32912
#define ID_FILE_SHELLOPEN               32914
#define ID_WINDOW_RESTORE               32915
#define ID_WINDOW_MINIMIZE              32916
#define ID_WINDOW_MAXIMIZE              32917
#define ID_EDIT_CODE2SJIS               32918
#define ID_EDIT_CODE2EUC                32919
#define ID_EDIT_CODE2JIS                32920
#define ID_VIEW_TOOLBAR_WND             32923
#define ID_VIEW_TOOLBAR_TOOLS           32924
#define ID_VIEW_TOOLBAR_FIND            32925
#define ID_VIEW_TOOLBAR_EDIT            32926
#define ID_VIEW_TOOLBAR_JMP             32927
#define ID_VIEW_TAB_2                   32928
#define IDW_TOOLBAR_EDIT                32929
#define IDW_TOOLBAR_FIND                32930
#define IDW_TOOLBAR_TOOLS               32931
#define IDW_TOOLBAR_WND                 32932
#define IDW_TOOLBAR_JMP                 32933
#define ID_EDIT_EXECMAILER              32934
#define ID_FILE_SENDMAIL                32935
#define ID_EDIT_CRLF                    32936
#define ID_EDIT_LF                      32937
#define ID_EDIT_CR                      32938
#define ID_EDIT_INSQUOTE                32939
#define ID_EDIT_DELCPPCOMMENT           32940
#define ID_EDIT_DELVBCOMMENT            32941
#define ID_EDIT_DELASMCOMMENT           32942
#define ID_EDIT_DELQUOTE                32943
#define ID_FILE_MAILLIST                32944
#define ID_EDIT_KAIGYOCONV              32945
#define ID_CHANGE_INSMODE               32946
#define ID_HELP_CONTENT2                32948
#define ID_CUSTOMIZE_TOOLBAR            32950
#define ID_CUSTOMIZE_TOOLBAREDIT        32951
#define ID_CUSTOMIZE_TOOLBARFIND        32952
#define ID_CUSTOMIZE_TOOLBARJMP         32953
#define ID_CUSTOMIZE_TOOLBARTOOLS       32954
#define ID_CUSTOMIZE_TOOLBARWND         32955
#define ID_EDIT_ALLUNDO                 32956
#define ID_EDIT_ALLREDO                 32957
#define ID_HTTP_FILE_OPEN               32958
#define ID_EDIT_FCOMP_TABEQUAL2SPACE    32959
#define ID_EDIT_FCOMP_ZENEQUAL2HAN      32960
#define ID_EDIT_FCOMP_ALPHABETBIGANDSMALL 32961
#define ID_EDIT_SOURCEARRANGE           32962
#define ID_EDIT_FILERECOMPARE           32963
#define ID_INDICATOR_GYORETU            61446
#define ID_INDICATOR_INS                61447
#define ID_INDICATOR_TIME               61450
#define ID_INDICATOR_READONLY           61451
#define ID_INDICATOR_CHARCODE           61483
#define ID_INDICATOR_BYTE               61484
#define ID_STATIC                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        760
#define _APS_NEXT_COMMAND_VALUE         32964
#define _APS_NEXT_CONTROL_VALUE         1272
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
